### ISSUE TITLE
Create Unique Task Decorator

### ISSUE THREAD

**Issue by nickburns2006** [custom-components/pyscript#1]
The convention of declaring `task.unique(‘function_name’)` seems a bit non-pythonic.

I feel like it might be better to create a `@unique` decorator that ensures that the method it wraps is only run once.

Could even add a param that will control what that means:

- `@unique` or `@unique(“restart”)` would kill the previous run
- `@unique(“queue”)` would enqueue subsequent calls.

I’m sure there are more cases, just spit-balling.

**Comment by craigbarratt** [comment]
Thanks for the great suggestion - I totally missed the idea of making `unique` a decorator. That's much more natural. I don't think there are many cases where the `task.unique()` function would be in the middle of some code, but I'll keep it around just in case that's needed.  Let me think about the specific decorator name and arguments.  I'm working on supporting Jupyter as a pyscript frontend currently, and I'll get to this after that.

**Comment by craigbarratt** [comment]
I created a [wiki](https://github.com/custom-components/pyscript/wiki/Roadmap-for-Pyscript) with some roadmap ideas, and I added this idea to that list.  So closing this issue.

**Comment by craigbarratt** [comment]
Just did commit 59a5461 that adds `@task_unique` as a new decorator.  Its arguments are the same as `task.unique()`.
