### ISSUE TITLE
Builtin 'open()' function not recognized

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#101]
I wanted to load a YAML file into a script:

```
@service
def message_zigbee(**data):
    with open("zigbee_rf433.yaml") as f:
        config = yaml.safe_load(f)
    log.info(data)
    # check if device is registered
    device = data['topic'].split('/')[1]
    if device in config['zigbee']:
        log.debug(f"found device {device}")
    else:
        log.warning(f"unknown Zigbee switch {device}")
```

The script is correctly loaded when resstarting `pyscript` but when it receives data, it crashes with:

```
2020-11-30 16:44:21 ERROR (MainThread) [custom_components.pyscript.file.zigbee_rf433.message_zigbee] Exception in <file.zigbee_rf433.message_zigbee> line 5:
        with open("zigbee_rf433.yaml") as f:
             ^
NameError: name 'open' is not defined
```

I am not sure whether I made an obvious mistake, or [`open()`](https://docs.python.org/3.8/library/functions.html#open) is somehow undefined?

Note: while reading the documentation, I discovered https://hacs-pyscript.readthedocs.io/en/stable/reference.html#accessing-yaml-configuration which I could use but my YAML file is large and I would prefer to keep it next to the script.

**Comment by dlashua** [comment]
`open` is one of the python builtins that are "forbidden" because they perform blocking I/O.

There are several ways around this. However, for something as simple as loading a YAML file, the easiest way is to include it in the configuration. If you want it in a separate file, that's still possible with the use of YAML includes.

**Comment by wsw70** [comment]
Thank you. 

I will copy the YAML into a string and read it from there (which will not complicate the code too much and indeed I remember now reading about blocking calls in `pyscript`)
