### ISSUE TITLE
Proposal: lower pyscript-generated logging level (or have two loggers)

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#108]
My experience with logging is the following:

- DEBUG: not something you normally see, useful for developers
- INFO: something normal happened in the course of the program and I, as the developer, want **the user (not me)** to know it
- WARNING: something bad happened but never mind (we tried to reach an API, we failed but it will be tried in a few moments again and we do not care if we missed that call - in my case typically when I pool for the current temperature outside)*
- etc.

With `pyscript` I want to tell in the log my beloved users (which incidentally is myself) that something expected happened (the shutters went up). For this I would use `log.info("fuite salle de bain ON")` (it is just an example for which I happen to have a log, this means that there is a leak in the bathroom...)

What I get is 

```
2020-12-03 12:39:02 INFO (MainThread) [custom_components.pyscript.file.fuite_eau.fuite_eau] {'trigger_type': 'state', 'var_name': 'binary_sensor.waterleak_sdb_water_leak', 'value': 'on', 'old_value': 'off', 'context': Context(user_id='7f8306dc8dff43db960be270adfcdfee', parent_id=None, id='34984ba49b4aba5ce7ff79f1d01d35eb')}
2020-12-03 12:39:02 INFO (MainThread) [custom_components.pyscript.file.fuite_eau.fuite_eau] fuite salle de bain ON
```

So for each of **my** INFO log, I also get one from **`pyscript`**. I do not think that this should happen because this is "logistical/debug" information for `pyscript` itself, not for code managed by `pyscript`. I think this should be at the DEBUG level.

Another possibility would be to have two loggers, one for `pyscript` itself, and one for the code ran through `pyscript` (and both could be set at different levels).

**Comment by dlashua** [comment]
I don't think that first line is from pyscript. Can you share your full pyscript? It looks like you're doing something like:

```python
@state_trigger('whatever')
def whatever(**data):
  log.info(data)
```

**Comment by wsw70** [comment]
@dlashua 

I do not know what to say - yes it is me being dumb. 5 lines of code and I managed to miss that (it was indeed a leftover `log.info(**data)` ).

Sorry :-|
