### ISSUE TITLE
prevent overwriting entity variables

### ISSUE THREAD

**Issue by basnijholt** [custom-components/pyscript#11]
I just accidentally did
```
light.living_room_lights = "off"
```
and now my lights in Home Assistant became unavailable.

Maybe it an idea to now allow overwriting entities? 

The same goes for `state`, `service`, `task`, etc.

**Comment by craigbarratt** [comment]
I don't know why they become unavailable.  Is it because the attributes get cleared when you do this?

This seems related to issue #9.

**Comment by craigbarratt** [comment]
With commit 712692f, state variable setting now preserves attributes.

**Comment by fleXible** [comment]
While playing around I came across a different problem regarding overwriting variables.
I seems, that declared variables take presedence over provided variables/objects.

Sample code:
````python
@time_trigger
def precende_problem():
    log.info(f"set_sensor_daytime_startup: running")
    event = None
    event.fire("raises Exception")
````
> precende_problem: running
Exception in <jupyter_0.precende_problem> line 35:
        event.fire("raises Exception")
        ^
AttributeError: 'NoneType' object has no attribute 'fire'

I came across this, when doing a for loop and naming the variable "state" without thinking too much about it.
It wouldn't be too much of an issue, if variables would be scoped, but as they are not, weird things can happen if you don't watch out.

**Comment by craigbarratt** [comment]
Variable scoping should be the same as Python, and I agree it would be a bug if it wasn't.  If you create a local variable it will overwrite a previously defined function or object.

The example looks correct to me.  This behaves exactly the same in Python and pyscript:
```python
bytes.fromhex("1234")
bytes = None
bytes.fromhex("5678")
```
The first call works, and the second one fails with an error:
```
AttributeError: 'NoneType' object has no attribute 'fromhex'
```
Here's another example that also works the same in Python and pyscript:
```python
import math
print(math.sqrt(2))
math = None
print(math.sqrt(2))
```
I agree there is a subtle difference in pyscript: yes, `event` or `state` don't exist as an object.  But if it does (ie: you set them to something), that takes precedence over the `event.fire` or `state.set` functions, which is the same behavior as regular Python.

**Comment by fleXible** [comment]
What you say makes sense, I just never happen to stumble upon it before. Issue can be closed.
