### ISSUE TITLE
[bug] Duplicated functions decorated with @service are not exposed as such

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#121]
I was debugging a time-based automation today that was not working and decided to expose it as a service. There was no way for me to make it seen in the HA dev tools.

I then realized that my code was similar to:

```
@service
def hello(**data):
    log.info("hello 1")

@service
def hello(**data):
    log.info("hello 2")
```

Specifically: I mistakenly called two functions the same. 

There was no message in the HA logs about this. While it is conceivable that two functions are called the same (this is correct Python code and the second function wins) it is probably a mistake.

The fact that the service is not exposed is more "bug-like" and I guess that maybe some warning should be issued.

This is really low priority and I do not actually know whether this even qualifies as a bug, I just wanted to mention that in case it is by design and not documented.

**Comment by dlashua** [comment]
There may be something @craigbarratt can do about this, but, in general, this is just how Python works.

`def whatever()` just means to store the following function in a place called "whatever". It's functionally similar to `whatever = 15`. If you, then later, issue `whatever = 20` then it does, with no complaint. And if you later issue `def whatever():` again, it does so without complaint as well. The function is just like any other variable. In fact, you can "def whatever():" and then later "whatever = 15" in the same scope (file, whatever)... and your `whatever` function is gone, with no complaint.

**Comment by wsw70** [comment]
Yes, I completely understand that part - this is why I mentioned that the two defs are correct Python code.

I just thought that in the context of automations this is probably a mistake, and especially the fact that `@service` does not expose the service in that case is disturbing (sorry not an English speaker - I do not want to sound dramatic :)).

I will close the issue, that could be useful if someone finds it when searching fr a similar problem.

**Comment by craigbarratt** [comment]
While redefining a function is normal, as discussed, it is a bug that the 2nd definition isn't exposed as a service.  So re-opening until that bug is fixed.
