### ISSUE TITLE
importing lxml fails at HA restart but works when calling pyscript.reload

### ISSUE THREAD

**Issue by renede** [custom-components/pyscript#128]
Hi,

I am using pyscript to create an extended api for Frontier Silicon-based media players (based on the fsapi by Krasimir Zhelev).
For that I need the lxml.objectify module. 
I got it working quite well until I restarted HA. Then, the "from lxml import objectify" fails. It seems that the lxml import is incomplete (etree and objectify are missing). If later I call pyscript.reload, lxml is imported completely.

The simplest pyscript to reproduce this:
import lxml
log.info(f'{dir(lxml)},\nVersion = {lxml.__version__}')
from lxml import objectify
log.info(f'{dir(lxml)},\nVersion = {lxml.__version__}')

Log after a fresh HA start
INFO (MainThread) [custom_components.pyscript.file.fsapi2] ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'get_include'],
Version = 4.6.2
2020-12-27 03:28:16 ERROR (MainThread) [custom_components.pyscript.file.fsapi2] Exception in </config/pyscript/fsapi2.py> line 59:
    from lxml import objectify
    ^
AttributeError: module 'lxml' has no attribute 'objectify'

But after pyscript.reload:
INFO (MainThread) [custom_components.pyscript.file.fsapi2] ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_elementpath', 'etree', 'get_include', 'objectify'],
Version = 4.6.2
2020-12-27 03:42:29 INFO (MainThread) [custom_components.pyscript.file.fsapi2] ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_elementpath', 'etree', 'get_include', 'objectify'],
Version = 4.6.2

I'm running pyscript 1.1.0 under HA OS  2020.12.1 on a RPi 4B with OS 5.4.79-v7l and Python 3.8.6

PS: I'm new to github, and if I broke any posting rule, please tell me how to improve.

**Comment by renede** [comment]
Sorry, I forgot to mention that I have "allow_all_imports: true" in pyscript/config.yaml and "lxml" in pyscript/requirements.txt

**Comment by dlashua** [comment]
Welcome to GitHub!

When you post code, use 3 backticks before and after your code. That will keep your code from showing as:

lxml.__version__

instead of

```
lxml.__version__
```
... which is a big difference. :)

That being said, I get the same error regardless of whether it's a fresh start of Home Assistant, or after a `pyscript.reload`:

```
homeassistant    | 2020-12-27 05:41:19 INFO (MainThread) [custom_components.pyscript.file.test_lxml] ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'get_include'], Version = 4.6.2
homeassistant    | 2020-12-27 05:41:19 ERROR (MainThread) [custom_components.pyscript.file.test_lxml] Exception in </config/pyscript/test_lxml.py> line 3:
homeassistant    |     from lxml import objectify
homeassistant    |     ^
homeassistant    | AttributeError: module 'lxml' has no attribute 'objectify'
```

This tells me you likely have more code in your script that loads other modules or something into lxml (I've never used lxml so I'm not familiar with it). If you can post your entire script (fsapi2) it'll likley be a bit easier to figure out.

An internet search suggests that perhaps this is the right way to load `objectify`:

```
import lxml
log.info(f'{dir(lxml)}, Version = {lxml.__version__}')
import lxml.objectify
log.info(f'{dir(lxml)}, Version = {lxml.__version__}')
from lxml import objectify
log.info(f'{dir(lxml)}, Version = {lxml.__version__}')
```

Once I've done `import lxml.objectify`, then `from lxml import objectify` works fine. So, if somewhere else in your script you're doing `import lxml.objectify` or something like it, that would explain why it works on the second load, but not the first.

**Comment by renede** [comment]
Hi Dlashua,
Thanks a lot for helping so quickly!
For the test I had removed all other pyscripts (and none of them imported lxml)
The code I provided was the all the code there was, just to isolate the problem.
I tried your suggestion (as well as the 3 backticks ;-):
```
import lxml
log.info(f'import lxml gives:\n{dir(lxml)},\nVersion = {lxml.__version__}')
import lxml.objectify
log.info(f'import lxml.objectify gives:\n{dir(lxml)},\nVersion = {lxml.__version__}')
from lxml import objectify
log.info(f'from lxml import objectify gives:\n{dir(lxml)},\nVersion = {lxml.__version__}')
```
and this works!
```
2020-12-27 15:31:27 INFO (MainThread) [custom_components.pyscript.file.test_lxml] import lxml gives:
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'get_include'],
Version = 4.6.2
2020-12-27 15:31:30 WARNING (SyncWorker_3) [homeassistant.helpers.service] Unable to find services.yaml for the variable integration
2020-12-27 15:31:30 INFO (MainThread) [custom_components.pyscript.file.test_lxml] import lxml.objectify gives:
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_elementpath', 'etree', 'get_include', 'objectify'],
Version = 4.6.2
2020-12-27 15:31:30 INFO (MainThread) [custom_components.pyscript.file.test_lxml] from lxml import objectify gives:
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_elementpath', 'etree', 'get_include', 'objectify'],
Version = 4.6.2
```
I have been searching for hours on the internet, but I did not come across this solution. Could you please share the location where you found it, so that I may improve my search strategy?

**Comment by dlashua** [comment]
It was a bit of trial and error. The `lxml` documentation isn't great. But, I was able to test and see that "objectify" wasn't in the lxml object on import. I saw one reference to another lxml import working this way (https://lxml.de/api/lxml.usedoctest-module.html) and so I looked at the source (https://github.com/lxml/lxml/tree/master/src/lxml) and saw that all the pieces likely worked this way.

I don't know a lot about python modules that are written this way (with C backing modules), so I just took a gamble and tried it and it worked.

**Comment by renede** [comment]
Still, a bit strange that it did work on reload and that I didn't see this problem in 'regular' python on my desktop machine. Maybe related to the arm CPU of the RPi, and nothing to to with pyscript?
Btw, would have preferred a pure python module, but lxml was the only thing I could find to read some moderately complex xml strings directly into python data structures.
Thanks again, I will close the issue now.
