### ISSUE TITLE
Question: how does logging works with subdirectories?

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#135]
- https://hacs-pyscript.readthedocs.io/en/stable/reference.html#configuration explains the expected structure of the scripts.
- https://hacs-pyscript.readthedocs.io/en/stable/reference.html#logging explains how the logging is handled

Specifically `custom_components.pyscript.file.FILENAME.FUNCNAME` explains how one can set up detialed logging, and it works fine when I have `<config>/pyscript/FILENAME.py`.

**What about `<config>/pyscript/scripts/hello/FILENAME.py`?**

I tried to set `custom_components.pyscript.file.scripts.hello.FILENAME` as `DEBUG` and the debug messages do not appear (they do when I move the script up to `<config>/pyscript/FILENAME.py` and set `custom_components.pyscript.file.FILENAME`)

**Comment by dlashua** [comment]
"file" is for things in "/pyscript/". For things in "/pyscript/scripts/" "file" is replaced with "scripts". So, for `<config>/pyscript/scripts/hello/FILENAME.py` you'd use `custom_components.pyscript.scripts.hello.FILENAME`.

When in doubt, do `log.info('whatever')` from the location and look at the log line. 
```
homeassistant    | 2021-01-03 07:33:23 INFO (MainThread) [custom_components.pyscript.scripts.test_dir.test_file] this is a test
```
The part in [ ]'s is exactly what you'd put in `logger:`.

**Comment by wsw70** [comment]
Thank you Daniel. It is now clear.

I actually tried the trick you mentioned, but since my configuration was wrong and the generic HA logging is `ERROR` in my case I did not see anything (and did not think about using error or critical).
