### ISSUE TITLE
Issue/Dev Error: Cannot share variables between triggers

### ISSUE THREAD

**Issue by tal** [custom-components/pyscript#136]
I'm trying to use variables to manage state between invocations of one or several triggers. I'm not sure if this is something that's supposed to be possible or not, but the attached code never sets the variable on the outside.

```py
down_at = None
@service
def test_timer():
  nonlocal down_at

  log.error(f"down_at = {down_at}")

  if down_at is None:
    down_at = time.time()
  else:
    diff = time.time() - down_at
    log.error(f"time between: {diff}")
```

In this case the `down_at` variable is never set and is always `None`. I'm pretty new with python, so it could be that to, if so apologies for the ignorance.

I'd like to be able to store state this way instead of having to do `state.set` because of the hoops required for it, plus how it pollutes the public namespace.

Thanks

**Comment by dlashua** [comment]
Use "global" instead of "nonlocal".

**Comment by tal** [comment]
Thanks! I'll try and make a PR for the docs.
