### ISSUE TITLE
Question: how to get a list of devices, and their attributes?

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#138]
Getting states is [well documented](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#state-variables). 

I need to get a list of **devices** and from there build the list of entities that are attached to that device - I did not find this in the docs, is this possible with `pyscript`?

**Comment by dlashua** [comment]
Pyscript doesn't do anything to make accessing devices easier (yet!). However, if you have `hass_is_global` enabled in your configuration, you can access the entire `hass` object. If you dig through the Home Assistant code and developers documentation, you may be able to figure out what is needed for this.

If you do, please share some code snippets. I'd love to see some device centered features in pyscript.

**Comment by wsw70** [comment]
Thanks @dlashua. I will have to dig deeper then, because I not only need to retrieve the details of a device, but also the HA GUII-overwritten names of its entities (I create devices with a specific name, and then change them in the GUI when needed).

I will post that one I have gone through it (probably as a repo to the `genius_app` I mentioned earlier :))
