### ISSUE TITLE
class instance destructors are not called

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#146]
Test code:
```
class TestClass:
    def __init__(self):
        log.info('I am here')

    def __del__(self):
        log.info('I am gone')


@time_trigger('startup')
def startup():
    a = TestClass()
    task.sleep(3)
    del a
```

"I am gone" is never displayed.

Compare to python:
```
import time

class TestClass:
    def __init__(self):
        print('I am here')

    def __del__(self):
        print('I am gone')



a = TestClass()
time.sleep(3)
del a
```

**Comment by craigbarratt** [comment]
Good catch.  Part of the issue is the `__del__` method defined in pyscript is async, so the python destructor can't call it.  But even with a `@pyscript_compile` decorator it still doesn't work, which I'm still investigating.

**Comment by craigbarratt** [comment]
It should work now.  The `__del__` function requires the `@pyscript_compile` decorator, since it needs to be a regular function.  That means it can't use any pyscript features.  To confirm `__del__` is called I modified a global list, eg:
```python
called = []

class TestClass:
    def __init__(self):
        log.info('I am here')

    @pyscript_compile
    def __del__(self):
        called.append("__del__")
```
