### ISSUE TITLE
Discussion: unloading a context should be able kill all running tasks in that context

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#147]
Here's a simple and common motion activated lights type automation:

```python
@state_trigger('binary_sensor.motion == "on"')
def motion_detected():
  task.unique('motion_lights')
  light.room.turn_on()
  task.wait_until(state_trigger='binary_sensor.motion == "off"')
  task.sleep(300) # 5 extra minutes of delay
  light.room.turn_off()
```
As pyscript is now, if motion is detected and then I reload this script for whatever reason, the task to turn the lights back off is still running. In many cases, this is probably desired so it makes sense to do this. If pyscript didn't leave the task running, we'd, instead, need two automations: one to turn the lights on, and a separate one to turn them off once motion stopped. And, to be absolutely complete, we'd need them both to `state_check_now`. If the 5 minute delay was critical (i.e. having the delay be LONGER than 5 minutes when a reload occurred was not okay), we'd also need to persistently store the "off time", and deal with retrieving that.

All of this means, having pyscript do exactly what it does is best. However, when the alternative is needed, it's not even possible.

In the cases when we want that task to be killed, there is no way to do so aside from restarting all of Home Assistant. Adding the code to kill it after the fact doesn't work, because it's already running and the reloaded script can't see that old task. This can be the case when there was an oversight in the initial code or when the logic of a script changes drastically. It also happens when a script is deleted entirely.

I think it's better to require extra work to keep the task running, instead of requiring extra work (including a possible restart of Home Assistant) to kill it off. In most cases, if the timing of something is critical, I'm having to write the extra code anyway because I want the timing to survive a Home Assistant restart as well. And, in cases where the timing is not critical, writing two automations is simple enough. Or, alternately, sticking with one automation and manually turning the light off if it's in the wrong state after a reload.

Another option is to do BOTH. Have pyscript keep track of all the tasks created for each context (which I think it does already). If a context is destroyed without the intent to restart it, all tasks should be killed. If it's destroyed as part of a reload, the tasks can remain running, however, pyscript should not lose track of the old tasks so that, if later, it is destroyed, the old tasks can be killed too. Create a method like `task.kill_all_tasks()` that can be added at the top of a script. This will cause pyscript to kill everything associated with that context (except for the currently running task, of course). With this in place, if we don't want any tasks to survive, we call `task.kill_all_tasks()` at the top of the script. If we want the current functionality, we do nothing. And, even if we do nothing, when the script is deleted/commented out/removed from app config.... pyscript will kill them anyway because if there is any existing user code relying on the tasks of deleted scripts to keep running, that's a huge hack. 

Thoughts?

**Comment by craigbarratt** [comment]
You can kill any running task on reload by calling `task.unique` directly, not inside a trigger:
```python
task.unique('motion_lights')

@state_trigger('binary_sensor.motion == "on"')
def motion_detected():
    task.unique('motion_lights')
    ...
```
That doesn't handle the case where the script is only unloaded (eg, by commenting or removing it). So the better approach would be to do it inside a `shutdown` trigger:
```python
@state_trigger('binary_sensor.motion == "on"')
def motion_detected():
    task.unique('motion_lights')
    ...

@state_trigger('shutdown')
def stop_my_tasks():
    task.unique('motion_lights')
    ...
```
This should provide the flexibility you suggest - it's easy to explicitly kill tasks on reload if your application requires that.  I don't think it makes sense to reverse the default behavior.

**Comment by dlashua** [comment]
I absolutely missed that in the docs somehow, even though it's there perfectly. Thank you! This does exactly what I need.

**Comment by dlashua** [comment]
ahhh... I misunderstood you and the docs.

Calling `task.unique` outside of any trigger or method kills the task, but, only if that task also called `task.unique`,as your code shows above. 

So, if I've got 3 triggers in a file, my code will have to look like this:

```
@state_trigger('1')
def one():
  task.unique('1')

@state_trigger('2')
def two():
  task.unique('2')

@state_trigger('3')
def three():
  task.unique('3')

@time_trigger('shutdown')
def shutdown():
  task.unique('1')
  task.unique('2')
  task.unique('3')
```

While this does work, it's verbose. And it carries the caveat that I mentioned originally.... if I forget to give a trigger the `task.unique` treatment... adding it after the fact will not kill the task. Neither will any form of `pyscript.reload` that I can find. I have to restart Home Assistant. 

There might be something I can do starting with `pyscript.get_global_ctx()` in a shutdown function to find everything and kill it off. I'll dig deeper into that.

**Comment by dlashua** [comment]
It seems that while tasks are registered in `Function.our_tasks`, they are not grouped by global_ctx. So, it doesn't look like I can make this happen in a user script alone.

I'd need to add Function.global_ctx2task or perhaps GlobalContext.tasks, add tasks to it when created, and remove them when complete. Then a method like `task.kill_all_in_global_ctx()` could be added to iterate this list and kill everything, which could be used in a shutdown function or at the top of a script to ensure nothing is left running, even if `task.unique` wasn't used. Would this be okay, and do you have a preference which way it goes? I could make a PR if you're not against this.
