### ISSUE TITLE
Simple call service light not working

### ISSUE THREAD

**Issue by JohannCR** [custom-components/pyscript#148]
Hi,

I'm trying out pyscript and... got nothing. I don't understand why it just does not work on my setup.
Of course I tried reloading pyscript, reloading HA, nothing.

Here is a minimum example, very simple. It's in file
config/pyscript/flash_light.py

```
@service
def light_the_f_up(light_bulb=None):
  if light_bulb is not None:
    light.turn_on(entity_id=light_bulb, brightness=255)
    log.info(f"light_on({light_bulb})")
```
Called from a lovelace button card
```
type: button
  tap_action:
    action: call-service
    service: pyscript.light_the_f_up
    service_data:
      light_bulb: light.etoile
```

No error in the Log, only this :
2021-01-21 14:39:21 INFO (MainThread) [custom_components.pyscript.file.flash_light.light_the_f_up] light_on(light.etoile)

Of course the light.etoile entity works otherwise...

Env:
hass.io in docker container on DSM.
Version | 2021.1.4
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 4.4.59+
CPU Architecture | x86_64

Nothing much to go on... Any idea ? Thanks !

**Comment by wsw70** [comment]
Have you tried calling the service from the Dev Tools in HA?. It should shop up as `pyscript.light_the_f_up`

**Comment by JohannCR** [comment]
Thanks for your answer !
No luck. There is no pyscript in the dev tools... That's weird

**Comment by wsw70** [comment]
This is indeed strange since you have a log entry that shows that the component is installed correctly. I see for instance

![image](https://user-images.githubusercontent.com/1345886/105362417-2a540380-5bfb-11eb-8bdd-832e8337e001.png)

Can you try to call `homeassistant.turn_on(entity_id=light.etoile)` instead of the `light.turn_on()`?

**Comment by JohannCR** [comment]
Added `hass_is_global: true` and `homeassistant.turn_on(entity_id=light.etoile)` does the exact same nothing...

**Comment by JohannCR** [comment]
Just tried to reinstall pyscript, no change.
No pyscript.reload, no pyscript at all... Maybe something has gone wrong during install

**Comment by wsw70** [comment]
You installed `pyscript` via HACS? Do you see it correctly in the "Integrations" tab after installation?

**Comment by JohannCR** [comment]
Yes and yes

**Comment by wsw70** [comment]
Well, this is really strange. I see that you installed it on a Synology, in a docker container. I also use docker (though not on a Synology but on a server) so we should see the same.

I will ask a friend tonight who has a Synology how he installed his HA instance and will ask him to add pyscript to test.

**Comment by JohannCR** [comment]
I also tried stopping and relaunching the container FYI.
Ok thanks.

**Comment by wsw70** [comment]
No pb. Out of curiosity, this is what you see something like that in your `pyscript` custom component folder?

```
/etc/docker/data/hass/custom_components/pyscript(master*) # ls
config_flow.py  eval.py   function.py    __init__.py        logbook.py     mqtt.py      requirements.py  state.py      translations
const.py        event.py  global_ctx.py  jupyter_kernel.py  manifest.json  __pycache__  services.yaml    strings.json  trigger.py
```

In my case `/etc/docker/data/hass` is the root of HA (the place where `configuration.yaml` lives)

**Comment by dlashua** [comment]
I would "grep" the home assistant log file for any ERRORs and WARNINGs. If you don't have the pyscript services, something definitely went wrong.

(Also, just as a added bit, you don't need `hass_is_global` in order to use `homeassistant.turn_on`. `hass_is_global` provides access to a global variable called `hass` that is the real HASS Object inside of Home Assistant, for advanced use cases only. The only time I've ever used it is when I'm trying to test a weird idea that I eventually turn into a PR against pyscript).

**Comment by wsw70** [comment]
yes, @dlashua , do not hesitate to whip me publicly for misdirecting someone :) (who would have thought that there is a unicode Chinese symbol for whip: 鞭)

Now - my friend installed pyscript on his Synology (in a docker) and - surprise - **no `pyscript.reload` or `pyscript.*`** for that matter

**Comment by JohannCR** [comment]
It is in integration. Also tried to remove lines from config file and relaunch integration.
File structure different but not too much :
![Screenshot_20210121-223035](https://user-images.githubusercontent.com/7448079/105415032-8d17c000-5c38-11eb-9ea6-e37b83252185.png)

**Comment by JohannCR** [comment]
Hi, do you have any other idea of things I could try ? Thanks

**Comment by wsw70** [comment]
The only thing I can think of is to 
- remove the integration
- make sure that the folders are gone
- reinstall the docker image (if you have a persistent folder there will be no data lost)

The test on another Synology went on without problems (addition, then installation of the integration).

**Comment by dlashua** [comment]
Turn on debugging for pyscript. In `configuration.yaml`:

```
logger:
  default: info
  logs:
    custom_components.pyscript: debug
```

Then restart home assistant, wait for it to fully start, then navigate to `developer-tools/service` and look for `pyscript.reload` in the dropdown.

Then dump your `home-assistant.log` file into pastebin.com and link it here. We'll be able to find the issue that way.

**Comment by JohannCR** [comment]
Ok I'm back on rails. I've updated HA (no change), so reinstalled docker image. I see no changes except now I can find the pyscript service in devtools, so that's a good sign !
I've tried calling the service from devtools, still no light. Tried reloading pyscript too.
What's next ? Do you still want a home-assistant.log pastebin ?

**Comment by wsw70** [comment]
> Do you still want a home-assistant.log pastebin ?

Yes, this may show some issues

**Comment by JohannCR** [comment]
Damn I did not call the right service since reinstall... Rectified that and now it works ! Seems the docker image was the problem somehow ?
You can close the issue
Thank you guys for your help !

**Comment by wsw70** [comment]
> Seems the docker image was the problem somehow 

Make sure o have a persistent volume for your configuration

> You can close the issue

You can close the issue yourself ("Comment & Close" button)
