### ISSUE TITLE
Question: how to listen to several events of the same type

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#151]
The [documentation](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#function-trigger-decorators) states

> A single function can have any or all of the decorator types specified, but at most one of each type.

In such a case how can I monitor several events of the same type (say - two MQTT topics, or several actions)?

My current solution is to have intermediate functions, each having one decorator, and both calling the actual function that handles the event - but there may be a better solution?

**Comment by dlashua** [comment]
That's how I do it too: a function to do the work, and multiple functions with an `event_trigger` decorator on it that just calls the first function.

**Comment by craigbarratt** [comment]
For `@state_trigger` and `@time_trigger` you can specify multiple arguments (or lists of arguments), so a single function can be triggered by multiple state expressions or time specifications.

For `@event_trigger` and `@mqtt_trigger` you can currently only specify a single event or mqtt topic, although mqtt supports wildcards, so one trigger can capture multiple topics if they have similar names that can be matched by a wildcard.

`@event_trigger` could be extended to support multiple event names if there is interest.  In the meantime, @dlashua's solution is the best one in the few cases where a common handler function for different events is needed.

**Comment by Beiri22** [comment]
> For `@state_trigger` and `@time_trigger` you can specify multiple arguments (or lists of arguments), so a single function can be triggered by multiple state expressions or time specifications.

Please see https://github.com/custom-components/pyscript/issues/157
