### ISSUE TITLE
Question / Request: Multiple use of state_active-decorator

### ISSUE THREAD

**Issue by Beiri22** [custom-components/pyscript#156]
Hi, I just tried to use multiple @state_active-Decorators to split my conditions into logical groups. But it tells me:
```
decorator state_active repeated; ignoring decorator
```

Is it possible to allow the usage of multiple state_active-decorators on one function?

**Comment by wsw70** [comment]
No, it is not possible currently. 
See https://github.com/custom-components/pyscript/issues/151 for a solution using intermediate functions (if you are looking for an OR condition)

**Comment by Beiri22** [comment]
I'm not looking for the state_Trigger-Decorator, but the state_active-Decorator.

**Comment by craigbarratt** [comment]
Since `@state_active` takes a (single) python expression, you can easily combine multiple conditions into a single expression, eg:
```python
@state_active("sensor.example1 == 'on' or sensor.example2 == 'off' or sensor.example3 == 'on'")
```
or
```python
@state_active("""any([
        sensor.example1 == 'on',
        sensor.example2 == 'off',
        sensor.example3 == 'on',
    ])""")
```

**Comment by oxan** [comment]
For those finding this via Google, you can combine multiple conditions with a bit nicer syntax by using this wrapper:
```python
# Enable the automation only if all passed conditions are true
def conditional(conditions):
    def decorator(fn):
        expr = "all([" + ", ".join(conditions) + "])"
        @functools.wraps(fn)
        @state_active(expr)
        def wrapper():
            return fn()
        return wrapper
    return decorator
```

This allows you to write multiple conditions like this:
```
@conditional([
    "sensor.example1 == 'on'",
    "sensor.example2 == 'off'",
    "sensor.example3 == 'on'",
])
```


Having the `@functools.wraps(fn)` there is necessary to get correct automation names in the logbook, but requires `allow_all_imports` to be set to true.
