### ISSUE TITLE
Wiki: Writing an App in Pyscript

### ISSUE THREAD

**Issue by SVH-Powel** [custom-components/pyscript#161]
https://github.com/custom-components/pyscript/wiki/Writing-an-App-in-Pyscript

Isn't this document using deprecated methods according to the 1.1.0 release?

_However, the use of pyscript.config["apps"][YOUR_APP] to get application configuration is still available but now deprecated. The apps entry in pyscript.config will be removed in a future release. This is to prevent wayward applications from seeing configuration settings for other apps. The new pyscript.app_config variable should be used instead_

**Comment by craigbarratt** [comment]
Yes - good catch.  Perhaps @dlashua could update it, or you could instead.

**Comment by dlashua** [comment]
Fixed! Thanks!
