### ISSUE TITLE
RuntimeError: Cannot be called from within the event loop

### ISSUE THREAD

**Issue by Tolriq** [custom-components/pyscript#164]
Hi,

So I've been testing and using pyscript and it works quite well. But now that I'm trying to go a step deeper I'm facing a problem accessing hass.states to be able to list all entities and automate more things without having to know the entities list.

Something like that:

```
@time_trigger("startup")
def fix_covers_from_switches():
    for state in hass.states.all():
```

Triggers an error:
```
for state in hass.states.all():
^
RuntimeError: Cannot be called from within the event loop
```

And I don't really know how to fix that.

**Comment by Tolriq** [comment]
Ok found in HASS doc async_all and as_dict are necessary when accessed from async code.

**Comment by dlashua** [comment]
For MOST things, there is usually a pyscript way to do what you want without having to rely on the "hass" variables and digging through Home Assistant Developer Docs. In this case, `state.names()` does what you're looking for, I think.

https://hacs-pyscript.readthedocs.io/en/stable/reference.html#state-variable-functions

**Comment by Tolriq** [comment]
Thanks I've read that doc a lot of times and use all the rest of the state functions and missed that one each times :(
state without s and the **names** so far from the **all** I see from normal way in samples, completely lost me I suppose.

Way cleaner that way.
