### ISSUE TITLE
Feature Request: get scene contents

### ISSUE THREAD

**Issue by tal** [custom-components/pyscript#166]
I'd love the ability to get the values for each entity that a scene has set. The reasoning for this is to be able to be able to apply these scenes in methods that I have automated elsewhere in pyscript.

My specific example is creating a service that sets the max/min value for a light. I'd love to be able to use the UI to create/edit scenes and then have my automation use this service. This way may spouse can also edit the values for scenes and the like.

Thanks!

EDIT:

The way I've hacked it so far is as follows. I don't really like it, but It works

```python
@service
def list_scene(entity_id=None, **kwargs):
    attr = state.getattr(entity_id)
    scenes = pyscript.config["global"]["scenes"]

    for scene in scenes:
        if scene["id"] == attr["id"]:
            log.error(f"{scene}")
```

configuration.yaml
```yaml
pyscript:
  global:
    scenes: !include scenes.yaml
```

**Comment by dlashua** [comment]
Sadly, the internals of "scenes" aren't exposed through the entity system. So, if this is even possible (without changes to HASS) it would mean finding a way to access the actual internal HASS scene objects, and enumerating their internal variables. Generally a bad idea, since these things can change leaving pyscript broken.

In my opinion, scenes are one of the more underbaked HASS features. Your solution is pretty elegant, I think, by including 'scenes.yaml' into your pyscript config. This won't help with scenes created using `scene.create`, but, otherwise, it seems to work quite well.

**Comment by tal** [comment]
Unfortunately the problem for my use case is that my whole goal is to allow my spouse to edit the scenes using the UI. Unfortunately though by importing the yaml I'd have to restart all of hass to get it to update the values.

At this point I see why you wouldn't/couldn't integrate it directly. Is there a way to either lazily load the yaml or somehow automate the reloading of it upon scene change?

**Comment by dlashua** [comment]
I think there is a scene.reload service to cause Home Assistant to reload the scene definitions if you've altered them (manually or via some pyscript code). 

If I were going to do this I would write my own "scene.create" and "scene.apply" services in pyscript. Each room in my home would have a preconfigured list of devices that will be saved for the scene. A input_select would present the room options, a input_text would provide the scene name, and a service call would start the pyscript.scene_create service. It would look at the room and name sent in the service call and save the state of those entities. when pyscript.scene_apply is called it looks up the room name and scene name and restores all the states if it exists. It's basically a complete rewrite of the Home Assistant "scene" stuff in pyscript. Though you could reuse the scene.apply service call from HASS to actually set the states of things if you so desired.

**Comment by tal** [comment]
Is there a way to have pyscript reload the config vars? And if I do that does it follow the import?

**Comment by dlashua** [comment]
If you make it an "app" and put the config in the "app config" it'll pyscript will reload whenever it changes:

```
pyscript:
  apps:
    my_scene_app:
      scenes: !include scene.yaml
```

Then in your app code `pyscript.app_config['scenes']` will have the data.

**Comment by tal** [comment]
Ah thanks! This is definitely workable for me.

**Comment by craigbarratt** [comment]
If you put `scene.yaml` in or below the `pyscript` folder then any changes to that file will be auto-detected.  That will cause all the yaml config to be reloaded, and if your app's config settings change then the app will be reloaded.

**Comment by tal** [comment]
Unfortunately then it wouldn't be editable by the front end UI right?

**Comment by tal** [comment]
> Then in your app code `pyscript.app_config['scenes']` will have the data.

Probably a separate issue but i'm getting this:

```
        scenes = pyscript.app_config['scenes']
                 ^
NameError: name 'pyscript.app_config' is not defined
```

**Comment by dlashua** [comment]
I haven't played with the frontend scene creator... but if it just, ultimately, stuffs YAML into scenes.yaml, it'll work just fine. If it stores it somewhere else, then, no, probably not.

**Comment by tal** [comment]
seems like a `scene_reloaded` event gets triggered with changes in the UI. So I can hook onto that. Thanks so much w/o this thread I definitely wouldn't have been able to get this to work!
