### ISSUE TITLE
Can't call domain services using domain.entity.service() pattern

### ISSUE THREAD

**Issue by Nxt3** [custom-components/pyscript#173]
I used to be able to do:

```python
light.master_bedroom.turn_on(brightness=254, color_temp=275)
```

but now I get errors:

```
AttributeError: 'StateVal' object has no attribute 'turn_on'
2021-02-26 16:06:29 ERROR (MainThread) [custom_components.pyscript.file.daytime.turnOnDayLights] Exception in <file.daytime.turnOnDayLights> line 9:
            light.master_bedroom.turn_on(brightness=254, color_temp=275)
            ^
AttributeError: 'StateVal' object has no attribute 'turn_on'
```

I recently upgraded my core version to `core-2021.3.0b1`; might have something to do with this?

**Comment by craigbarratt** [comment]
On startup, pyscript calls `async_get_all_descriptions()` to get all the service descriptions, and it populates the dictionary `State.service2args` with all the services that have an `entity_id` keyword argument.  Assuming you have `allow_all_imports` and `hass_is_global` both set, you can check what services it knows about:
```python
from custom_components.pyscript.state import State
State.service2args["light"]
```
Does that include an entry `State.service2args["light"]` and `State.service2args["light"]["turn_on"]`?

If not, you can call `async_get_all_descriptions()` to see what it returns for "light":
```python
from homeassistant.helpers.service import async_get_all_descriptions
async_get_all_descriptions(hass)["light"]
```

**Comment by raman325** [comment]
I'm having the same issue, and I suspect it was the last pyscript release but haven't been able to dig in yet. Will run some tests based on your comment and will report back what I find

**Comment by craigbarratt** [comment]
I created an `input_number`:
```yaml
input_number:
  x1:
    initial: 100
    min: 0
    max: 1000
```
and I confirmed that things like `input_number.x1.increment()` and `input_number.x1.set_value(50)` work ok.

Perhaps there is now some race condition where the `lights.turn_on` service is not registered before pyscript calls `async_get_all_descriptions()`?  It should be called when the `EVENT_HOMEASSISTANT_STARTED` is fired, but perhaps something is broken now.  It is also called on `pyscript.reload`.

You could also call it manually from Jupyter with:
```python
from custom_components.pyscript.state import State
State.get_service_params()
```
Does it now work after you do that?

Also, in looking at the code I noticed that pyscript fails to update `State.service2args` when a new service is defined with an `entity_id` parameter, so pyscript services don't support these virtual methods.  I need to fix that.

**Comment by raman325** [comment]
I misspoke about it being tied to 1.3.0. When I downgraded, I saw my pyscript services in Dev Tools so I assumed everything was ok. But the next time an automation ran that called one of those services, it failed, so I'm guessing there was a change that's coming in the next release that's causing this behavior as I am still running on 2021.3.0beta2.

Running that command in Jupyter did not resolve the issue:
`Exception in <file.climate.set_temperature> line 47: climate.thermostat.set_temperature(temperature=float(temp)) ^ AttributeError: 'StateVal' object has no attribute 'set_temperature'`

**Comment by craigbarratt** [comment]
@raman325  - does the simple `input_number` test work or fail for you?

Unfortunately I don't have good internet access for the next day (or potentially 3 days).  I don't think I can upgrade to 2021.3.0beta2 until I have better internet.

**Comment by craigbarratt** [comment]
I successfully upgraded hass; the `input_number` test fails for me now.  Onto debugging...

**Comment by craigbarratt** [comment]
Hmmm, the return value of `async_get_all_descriptions()` does not include any `entity_id` fields, so pyscript doesn't consider it a valid virtual method.

**Comment by raman325** [comment]
ah, I know what's going on. The latest release introduces a new key to service calls called `target`. Now, in addition to specifying the `entity_id` in the service data dictionary, you would specify it under target. This has resulted in service schemas changing

Here are some references:

- https://developers.home-assistant.io/docs/dev_101_services#service-descriptions
- https://developers.home-assistant.io/docs/documenting/yaml-style-guide/#service-targets

**Comment by craigbarratt** [comment]
Yes, your explanation sounds right.  It looks like entity services are now a different thing, so we need to figure out how to enumerate them (or ideally just check a single one on demand, which would be better than caching them all at startup).

**Comment by raman325** [comment]
Wow you are fast, I logged in this morning to try to figure this out and wondered how you had already had a check for the `target` key. Confirmed that the latest commit resolves it!

One thing that came to mind is that it would be nice if we could use `target` (when this is included, there is a nicer UI available to pick entities) and `selector` (also enhances the UI) in service descriptions. It looks like it should just work if the docstring is `yaml`, but something to think about if you want to support it using non YAML docstrings.

**Comment by raman325** [comment]
Here's what it looks like in Dev Tools when you specify `selector`s in the service description btw:
![image](https://user-images.githubusercontent.com/7243222/109394152-83e2d880-78f3-11eb-9f5b-d40c0da3105b.png)

**Comment by craigbarratt** [comment]
Release 1.3.1 with this fix.

**Comment by Nxt3** [comment]
Thank you for your work on this amazing project! Really makes automating fun.
