### ISSUE TITLE
Warning message in the log: Detected I/O inside the event loop

### ISSUE THREAD

**Issue by kompre** [custom-components/pyscript#178]
Hi, 

I got this warning but otherwise the script works as I intended. 
It says to report it to the author of pyscript, so here it is.

```
Logger: homeassistant.util.async_
Source: util/async_.py:129
First occurred: 8:18:42 (4 occurrences)
Last logged: 8:18:45

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for pyscript doing I/O at custom_components/pyscript/eval.py, line 1899: return func(*args, **kwargs)
```

**Comment by craigbarratt** [comment]
It because your pyscript code is calling functions that do I/O.  See the [docs](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#avoiding-event-loop-i-o).
