### ISSUE TITLE
default zigbee2mqtt names for entities lead to invalid syntax for state triggers

### ISSUE THREAD

**Issue by sfiel** [custom-components/pyscript#180]
Hi,

By default zigbee2mqtt names the entities according to their address, but when using these names for example as state_trigger it is an invalid syntax:
```
@state_trigger("binary_sensor.0x00158d0003946123_occupancy == 'on'")
def test():
    log.info('test')
```
leads to
```
    binary_sensor.0x00158d0003946123_occupancy == 'on'
                 ^
SyntaxError: invalid syntax (scripts.motion_senors.hallway.test @state_trigger(), line 1)
```

when I rename the entiy for example to binary_sensor.living_room_occupancy it works as expected.

pyscript: 1.3.1
home assistant: 2021.2.3

Cheers,
Stefan

P.S.: thanks for your efforts!

**Comment by craigbarratt** [comment]
This is issue #165.  Since python is parsing the code, it doesn't allow literals that start with digits.  Staring in 1.3.0 the `watch` keyword was added, so you can use `state.get` inside a trigger expression, and `watch` to tell it what variables to monitor:
```python
@state_trigger("state.get('binary_sensor.0x00158d0003946123_occupancy') == 'on'", watch=["binary_sensor.0x00158d0003946123_occupancy"])
def test():
    log.info('test')
```
