### ISSUE TITLE
Autoload py files in subfolders

### ISSUE THREAD

**Issue by kennetjuh** [custom-components/pyscript#195]
Hello, first of all thank you for the pyscript component. I really love it and have rewritten all of my automations to use pyscript.

I would like to organize my files into subfolders.
I know it's possible to use the modules folder and use the import, but it's not sufficient to keep my file stucture clean.

**Comment by craigbarratt** [comment]
Everything below the `scripts` directory is autoloaded (including subdirectories to any depth).

**Comment by kennetjuh** [comment]
Thank you for your comment, I did not find this in the documentation, but maybe I overlooked it.
