### ISSUE TITLE
Can't parse sunrise + 60min in time_trigger check

### ISSUE THREAD

**Issue by iot49** [custom-components/pyscript#196]
pyscript logs `Can't parse sunrise + 60min in time_trigger check` for the following code:

```python
front = "switch.front_loft_light"

@time_trigger("sunrise + 60min")
@state_active(f"{front} == 'on'")
def front_light_off():
    switch.turn_off(entity_id=front)
```

The error occurs even for just "sunrise" or when dropping the `@state_active(f"{front} == 'on'")`.

**Comment by craigbarratt** [comment]
You are missing a `once()` (which means daily because the time spec doesn't include a date); try this:
```
@time_trigger("once(sunrise + 60min)")
```

**Comment by iot49** [comment]
That did it (how embarrassing)!

Thanks. Closed.
