### ISSUE TITLE
HA 2021.5.0: Exception: 'sunset+15m' not defined at this latitude

### ISSUE THREAD

**Issue by bob-tm** [custom-components/pyscript#203]
After updating to HA core-2021.5.0 

@time_trigger("startup", "once(sunset+15m)", "once(02:00:00)", "once(sunrise-15m)")

stop working
with exception:
2021-05-06 18:36:31 WARNING (MainThread) [custom_components.pyscript.trigger] 'sunset+15m' not defined at this latitude

I checked the HA Sun object at dev page and it looks ok with correct values.
Before update everything works fine.

**Comment by bob-tm** [comment]
this is the problem? 
https://github.com/home-assistant/core/pull/48573

**Comment by DanielWinks** [comment]
I've also been seeing the "sunset is not defined at this latitude" error. Also on 2021.5.x.

**Comment by craigbarratt** [comment]
Yikes. @bob-tm - your diagnosis is correct.  Thanks for tracking down the cause.

I just pushed a fix that should work for 2021.5 and also be backward compatible.  Can you try the master version and confirm it works?

There are some commit test errors but they are unrelated and I'll fix them later.

**Comment by bob-tm** [comment]
tnx. fixed!

**Comment by wsw70** [comment]
I overwrote the HACS installed `pyscript` with the `master` version and there are no more errors, thanks a lot for fixing this!

A related question: now that I have the `master` version in `custom_compoennts` - will HACS still suggest me a new version when it is officially released? Or do I have to go full manual from now on?

**Comment by wsw70** [comment]
Thanks @dlashua. This is also the info I got in the HACS discord.
