### ISSUE TITLE
task.unique() and @task_unique() not working as expected

### ISSUE THREAD

**Issue by dorbitbrown** [custom-components/pyscript#210]
I have a function that applies logic to set values in group of interrelated input_booleans, all of which are monitored by the function's @state_trigger decorator. I'm using task.unique() to avoid an infinite loop, except the loop is not avoided.  Since I need the function to assign values to the triggering booleans, I am using kill_me = True to kill any new instances of the function which get triggered by its changes to the booleans. The results are similar with kill_me = False.

Here is a minimal, reproducible  example of the problem:

1. In configuration/helpers, create two toggles: input_boolean.test_a, and **input_boolean.test_b
2. Add them to a card on the dashboard
3. Put these functions in a script file and load it:
@state_trigger('input_boolean.test_a')
def unique_test_a():
    task.unique('unique_test_a', kill_me=True)
    input_boolean.test_a = 'off' if input_boolean.test_a == 'on' else 'on'
    log.info(f"input_boolean.test_a == {input_boolean.test_a}")
.
@task_unique('unique_test_b', kill_me=True)    
@state_trigger('input_boolean.test_b')
def unique_test_b():
    input_boolean.test_b = 'off' if input_boolean.test_b == 'on' else 'on'
    log.info(f"input_boolean.test_b == {input_boolean.test_b}")
4. On the dashboard, toggle either of the buttons created in #1.  They will start flickering and toggling repeatedly.  That the states are indeed toggling can be seen in the log file, which will be filled with output like:
2021-05-28 14:38:36 INFO (MainThread) [custom_components.pyscript.scripts.mkwd_main.unique_test_a] input_boolean.test_a == off
2021-05-28 14:38:36 INFO (MainThread) [custom_components.pyscript.scripts.mkwd_main.unique_test_a] input_boolean.test_a == on
2021-05-28 14:38:36 INFO (MainThread) [custom_components.pyscript.scripts.mkwd_main.unique_test_a] input_boolean.test_a == off
2021-05-28 14:38:36 INFO (MainThread) [custom_components.pyscript.scripts.mkwd_main.unique_test_a] input_boolean.test_a == on
2021-05-28 14:38:36 INFO (MainThread) [custom_components.pyscript.scripts.mkwd_main.unique_test_a] input_boolean.test_a == off

**Comment by dlashua** [comment]
`task_unique` and `task.unique()` will only kill tasks that are actively running. In both of your test cases the trigger function is no longer executing when `task_unique` is applied. If you add a `task.sleep(5)` to the end of either of those trigger functions (just to make them live longer) you'll likely see these test cases working as expected.

**Comment by dorbitbrown** [comment]
Aha!  Got it!

Thank you.
