### ISSUE TITLE
Feature Request: Reusable Functions 

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#23]
I tend to reuse the same logic for various rooms, the only difference is the entities that get watched and acted on. This is also VERY useful for sharing "apps" that are configurable.

However, I can't seem to find a nice way to make code reusable in pyscript.

For instance, this was the closest I could come, but it still doesn't work:

```python
def follow_me(leader=None,followers=[]):
    log.error('creating trigger for {}'.format(leader))

    @state_trigger("True or {}".format(leader))
    def follow_me_trigger():
        log.error('follow me triggered for {}'.format(leader))
        value = state.get(leader)
        if value == 'on':
            for item in followers:
                homeassistant.turn_on(entity_id=item)
        else:
            for item in followers:
                homeassistant.turn_off(entity_id=item)

    return follow_me_trigger

follow_me('input_boolean.test_1', ['input_boolean.test_2'])
follow_me('input_boolean.test_3', ['input_boolean.test_4'])
```

Is there a recommended way to do this already? If not, would you consider adding such a feature?

**Comment by craigbarratt** [comment]
Ah - great point.  There isn't a good way to do this currently.  I do like your use of a closure, and as you note that doesn't work currently.  Let me think about how to best support this.

**Comment by craigbarratt** [comment]
I just pushed a commit 8834dc1 that should allows trigger closures to work. Closures were also broken, so I fixed those with an earlier commit.

The way it works is very similar to what you wrote.  However, the function trigger is destroyed if the function itself no longer has any reference to it in any scope.  So in your example, you will want to assign the return value of `follow_me` to a variable:
```python
f1 = follow_me('input_boolean.test_1', ['input_boolean.test_2'])
f2 = follow_me('input_boolean.test_3', ['input_boolean.test_4'])
```
If you re-assign, or delete, `f1` or `f2` then that trigger function will be destroyed.  That's consistent with the current behavior, which only worked in the global context - if you redefine a function in the global context, the old one is destroyed.

You could put all the closure function functions into a list if that is easier - all that matters is there is some reference to the function for it to survive, eg:
```python
trigger_funcs = [
    follow_me('input_boolean.test_1', ['input_boolean.test_2']),
    follow_me('input_boolean.test_3', ['input_boolean.test_4']),
]
```
or
```python
trigger_funcs = []
for i in range(1, 5, 2):
    trigger_funcs.append(follow_me(f'input_boolean.test_{i}', [f'input_boolean.test_{i+1}'])
```
Caveat - the cumulative changes were pretty significant, and it's only minimally tested.  But please try the master version and see if it works for your use case.

**Comment by dlashua** [comment]
Excellent!

I'll give this a shot later today and report back! Thanks!

**Comment by dlashua** [comment]
It seems to work as expected. Thank you for adding this!

**Comment by craigbarratt** [comment]
Thanks for proposing it, and thanks for confirming it works.
