### ISSUE TITLE
Script do not appear in the services Tab

### ISSUE THREAD

**Issue by juanitoddd** [custom-components/pyscript#245]
Hello friends,

Was wondering what am I doing wrong:

I have a docker HA instance running with the HACS Integration on it.
I Installed pyscript using the HACS store and after creating a basic script under `/pyscript/scripts/hello.py`

I can see in the logs that HA has loaded the script:
`[custom_components.pyscript.global_ctx] Loaded /config/pyscript/scripts/hello.py`

However, after reloading the pyscript integration, I can not find the service anywhere

My HA configuration.yaml looks like:
```
...
pyscript: !include pyscript/config.yaml
...
```

and my pyscript config.yaml:

```
allow_all_imports: true
hass_is_global: true

```

has someone a hint ? Thanks in advance

**Comment by juanitoddd** [comment]
Allright, I found the issue and I will post the fix in case someone has it too:

The python scripts should be in the form:

```
@service
def hello():
    """hello_world example using pyscript."""
    log.info("Hello")
```

**Comment by dlashua** [comment]
@juanitoddd if this issue is resolved, please close it.
