### ISSUE TITLE
Exception in </config/pyscript/main.py> line 10: from discord.ext import commands ^ AttributeError: module 'discord.ext' has no attribute 'commands'

### ISSUE THREAD

**Issue by Johno95CZ** [custom-components/pyscript#248]
Exception in </config/pyscript/main.py> line 10: from discord.ext import commands ^ AttributeError: module 'discord.ext' has no attribute 'commands'

Any tips how to run discord bot on a home assistant?
On the computer in PyCharm was everything working correctly.

**Comment by craigbarratt** [comment]
Pyscript does have known problems loading certain modules.  If you are having problems loading a module directly from pyscript, try doing it from a native python module (see the docs), and then calling that module from pyscript.

**Comment by ALERTua** [comment]
@Johno95CZ could you please update or close the issue? Thank you
