### ISSUE TITLE
Feature Request: pyscript/ subdirectories

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#26]
In line with recent changes to `master` to allow for "apps" and YAML based configuration, allowing subdirectories inside of pyscript/ would make keeping separate applications under revision control much easier. 

```
cd pyscript/
git clone http://github.com/dlashua/occupancy_manager.git
```

which would create files like:
```
pyscript/
  occupancy_manager/
    occupany_manager.py
    README.md
    configuration.sample.yaml
```

and allow commands like:
```
git pull
git commit
git push
```

This also lines pyscript applications up to be included in HACS (with HACS cooperation, of course) the same way that AppDaemon, NetDaemon, and python_script apps are included in the "Automations" section.

**Comment by craigbarratt** [comment]
Good point.  I agree having subdirectories for each app is better than trying to put them all into `apps`.

However, I'm not yet sure the best way to set this up, and specifically what to auto-load.  In each subdirectory, should it be:
* all `*.py` files
* just an `__init__.py` file, which would then import other files in that subdirectory (similar to how a package is set up)
* in a directory `my_app`, only load `my_app/my_app.py`
* specified in the configuration file, where the top-level parameter is the directory name:
    ```yaml
    pyscript:
      my_app:
        - load_files: x.py y.py
        - otherparams:
    ```
would load `my_app/x.py` and `my_app/y.py`.

**Comment by dlashua** [comment]
I like the idea of making it work like a package, just loading __init__.py. Especially if imports inside of that __init__.py would be able work against other files in that same directory (like a regular package).

If imports can't be handled with a "regular python" feel to them, then I think loaded all *.py files would be best.

**Comment by dlashua** [comment]
This sounds excellent!

**Comment by craigbarratt** [comment]
Implemented with referenced commit.
