### ISSUE TITLE
Send notification from pyscript

### ISSUE THREAD

**Issue by dellorogiulio** [custom-components/pyscript#274]
Hi everyone, 
I'm straggling with a strange behavior.  I'm try a simple thing: send a notification using pyscript.
I start with the following code:
```
def send_reminder():
    hass.services.call('notify', 'mobile_app_sm_xxxx', {
        'message': 'Something happened',
        'title': 'test' }, False)


@service
def auto_clean():
    send_reminder()
```
Using the [home assistant guide](https://www.home-assistant.io/integrations/python_script) as reference and trying to call directly the hassio service. If I call this service (_auto_clean_) hassio freezes and reboots after some minutes.  😵‍💫

So I try googling for pyscript-specific solutions and I find [issue 200](https://github.com/custom-components/pyscript/issues/200). Here I see the following code:
```
notify.mobile_app(
   message = "Something happened at home!",
   actions = [
      {'action': 'ALARM', 'title': 'Sound Alarm'},
      {'action': 'URI', 'title': 'Open Url', 'uri': 'https://google.com'},
   ]
)
```
But, where the `notify` variable comes from? If I try to use that as a global variable I have a
`NameError: name 'notify' is not defined` so this is not a global variable.

Thanks in advance for the help!

**Comment by dlashua** [comment]
Pyscript uses "magic" variables. They aren't globals. "notify" is not defined. However, because notify.mobile_app is a valid Home Assistant service, pyscript maps any use of that to the corresponding Home Assistant Service Call.

So, in your case you can use:
```
notify.mobile_app_sm_xxxx(message="Something happened", title="test")
```

**Comment by dellorogiulio** [comment]
Oh! I get it! Thanks for the support!
