### ISSUE TITLE
not implemented ast ast_starred

### ISSUE THREAD

**Issue by D4RGAN** [custom-components/pyscript#285]
Hi I was trying to make a list of times for the @time_trigger which i could easily change with another function. 
So for example instead of writing `@time_trigger("once(17:15:05)","once(16:00:00)","once(08:35:45)")` i would have a list  `l = ["once(17:15:05)","once(16:00:00)","once(08:35:45)"]` then i could use this list in my @time_trigger like this `@time_trigger(l)`. This did not work because a String was wanted so after some googling I learned about unpacking and thought I found my solution (my programming knowledge is mostly from the internet, so I probabaly lack alot of basic understanding, sorry).

But when I tried `@time_trigger(*l)` I got the error "Exception in </config/pyscript/Test.py> line 47: @time_trigger(*l) ^ NotImplementedError: file.Test: not implemented ast ast_starred".

If I understand this unpacking is not implemented or am I doing somehting wrong? And would there be another solution to my problem?

Thank you for the help

**Comment by craigbarratt** [comment]
The `@time_trigger` decorator arguments are only parsed once when the function is defined.  So, while the arguments to `@time_trigger` can be variables or expressions, they are only evaluated at the time the function is defined.

To make `@time_trigger` dynamic, you need to redefine the function with the new `@time_trigger`. That can be done using inner functions or closures.  You can read about that [here](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#trigger-closures) in the docs.

**Comment by worgarside** [comment]
@D4RGAN how did you implement your solution to this?

**Comment by D4RGAN** [comment]
@worgarside I did as craigbarratt told me and made a function factory. Looks like this:

```
time_triggers = []

def time_trigger_factory(input_datetime,func_name):
    #log.error(f"Creating a time trigger for {func_name} at {input_datetime} [HH:MM:SS]")
    @time_trigger(f"once({input_datetime})")
    def func_trig():
        globals()[func_name]()
    time_triggers.append(func_trig)

```
Initially I wanted one function with multiple triggers but I ended up creating multiple (same) functions which all do the same but have different timestamps. Maybe it would have been possible to alter `@time_trigger(f"once({input_datetime})")` so that it creates multiple triggers at once, but somehow I did it the other way around. But it still works, so I'm fine with it=)

**Comment by TheSimpleZ** [comment]
Tbh, I'm not very well versed in python. Although, if the arguments to the trigger decorators are evaluated when the function is defined, shouldn't unpacking work if the list is statically defined? 

Here's a simplified version of what I'm trying to do:
```python
dist = ["int(proximity.home_phone1) <= 50", "int(proximity.home_phone2) <= 50"]
@state_trigger(
    *dist,
    state_check_now = True
)
def on_approach():
    log.info("you're close!")
```
Since no values are being dynamically calculated, I'd expect this to run just fine and print a log message whenever either proximity sensor has a state of less than 50. However, I get the same error as in the original post. 

Ofc, this could be solved with factory functions, but it would add a lot of boilerplate and it looks clumsy. The simple example above would have to be turned into:
```py
triggers = []
dist = ["int(proximity.home_phone1) <= 50", "int(proximity.home_phone2) <= 50"]

def on_approach_factory(trigger):
    @state_trigger(
          trigger,
          state_check_now = True
      )
      def on_approach():
          log.info("you're close!")

    triggers.append(on_approach)

for d in dist:
    on_approach_factory(d)
```

Is there any way to make unpacking work for these decorators or is this a python limitation?

**Comment by craigbarratt** [comment]
I pushed 5058fed to fix the expansion of *list in decorator function arguments.  This should allow your original code to work.

**Comment by ALERTua** [comment]
@D4RGAN could you please update or close the issue? Thank you

**Comment by D4RGAN** [comment]
@ALERTua yes of course.
Sorry I tought the issue would be resolved without my doing.
