### ISSUE TITLE
Can not use the import requests library with pyscript

### ISSUE THREAD

**Issue by j0hann3s** [custom-components/pyscript#293]
When importing 'requests' into my python script I get the following error when trying to use "requests.get() :

2022-01-05 16:23:03 ERROR (MainThread) [custom_components.pyscript.file.test] Exception in </config/pyscript/test.py> line 6:
url = requests.get("https://www.google.com/") ^ RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/pyscript/eval.py, line 1899: return func(*args, **kwargs)

**Comment by qui3xote** [comment]
I think you need to wrap the call in task.executor in order to make it async safe.

**Comment by j0hann3s** [comment]
Thanks for the tip! Using `@pyscript_executor` did the trick in front of a definition with the offending code in it. I have no idea what is happening here but that solved it.

**Comment by craigbarratt** [comment]
@qui3xote is right.  See [the docs](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#avoiding-event-loop-i-o) for more info.
