### ISSUE TITLE
<function> called with unexpected keyword arguments: entity_id, new_state, old_state

### ISSUE THREAD

**Issue by GollyJer** [custom-components/pyscript#316]
Piggy backing a little on my [finding of errors](https://github.com/custom-components/pyscript/discussions/310) in the `home-assistant.log`.

This isn't the exact code that initially led me to find this issue but I think it shows the most extreme example.

With this code...

```python
from homeassistant.const import EVENT_STATE_CHANGED

@event_trigger(EVENT_STATE_CHANGED)
def monitor_events():
    print("hello")
```
... this error shows up in the log.

![image](https://user-images.githubusercontent.com/689204/153514320-362ee965-1f7e-4e18-9217-ca446e64a111.png)

<br />
With this code...
<br />
<br />

```python
from homeassistant.const import EVENT_STATE_CHANGED

@event_trigger(EVENT_STATE_CHANGED)
def monitor_events(entity_id, new_state, old_state):
    print("hello")
```
... no errors show up in the log.

<br />

Added here in **Issues** instead of **Discussions** because I don't see anywhere in the docs that says it's required to put the named arguments so am guessing maybe bug?

Best,
Jeremy

**Comment by dlashua** [comment]
The [docs](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#event-trigger) indicate that each event will send different named arguments to the method it calls. It states:

> To figure out what parameters are sent with an event and what objects (eg: list, dict) are used to represent them, you can look at the HASS source code, or initially use the **kwargs argument to capture all the parameters and log them.

I guess the docs could specifically state "you absolutely must accept the named parameters that the event will send", but it was clear to me that this was required. I generally just use **kwargs and then dig out the things I need from there.

**Comment by GollyJer** [comment]
Yeah. I think this boils down to me not fully understanding decorators. You point is well taken.

My real world example was this.

```python
@event_trigger("hue_event", "type == 'short_release'")
def monitor_button_presses(id=None):
    area = id.removesuffix("_button")
    toggle_lights(area)
```

It worked as expected and I never noticed the errors being logged until I was trying to solve a different issue.

My new approach, given the info you provided, is to always add `**kwargs` to my decorated functions even if I'm not using it.

Thanks!

```python
@event_trigger("hue_event", "type == 'short_release'")
def monitor_button_presses(id=None, **kwargs):
    area = id.removesuffix("_button")
    toggle_lights(area)
```
