### ISSUE TITLE
Scripts not loading?

### ISSUE THREAD

**Issue by cjeri** [custom-components/pyscript#318]
Not sure if this is a bug or whether I'm doing something wrong. Downloaded pyscrit via HACS and installed / restarted per instructions. However, when I try to Call Service in an automation and try to select one of the scripts in the <config>/pyscript folder, only get presented with two options (none of them are the *.py files): "Pyscript Python scripting: Start Jupyter kernel" and "Pyscript Python scripting: Reload script"

**Comment by davidbd7** [comment]
Hi did you figure this out? I'm having the same problem. I've installed pyscript via HACS well and restarted and reinstalled multiple times. The only two scripts that show up are "Pyscript Python scripting: Start Jupyter kernel" and "Pyscript Python scripting: Reload script", just like you, even though I have custom services created through other python files in that folder. Anything will help!

**Comment by ALERTua** [comment]
@cjeri could you please update or close the issue? Thank you

**Comment by cjeri** [comment]
Fresh install solved it for me.
