### ISSUE TITLE
functions evaluated before they are called?

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#34]
```python
def both(msg):
    a(msg)
    b(msg)

def a(msg):
    log.info(f'in a {msg}')

def b(msg):
    log.info(f'in b {msg}')

both('test')
```

The above does not work in pyscript, however, it works in regular python.

```
Exception in </config/pyscript/test.py> line 1:
    def both(msg):
    ^
SyntaxError: no binding for nonlocal 'a' found
```

Moving the declaration of "both" down below "a" and "b" makes this work. However recursive functions like this wouldn't work:

```python
def show_hashes(num):
    hashes = ["#" for i in range(0,num)]
    log.info("".join(hashes))
    num -= 1
    if num <= 0:
        return
    show_dots(num)

def show_dots(num):
    dots = ["." for i in range(0,num)]
    log.info("".join(dots))
    num -= 1
    if num <= 0:
        return
    show_hashes(num)

show_dots(6)
show_hashes(6)
```

There are, of course, ways to rewrite this example to make it work, but I imagine there are some non-trivial cases where rewriting would be difficult.

**Comment by craigbarratt** [comment]
Oops - when I fixed variable scoping for closures (which has to be done at parsing time rather than runtime), it also insists on resolving global variables too, which should instead be done at runtime.  Fixed in 5ac1935.
