### ISSUE TITLE
Pyscript flooding logbook

### ISSUE THREAD

**Issue by glmnet** [custom-components/pyscript#347]
I have a script 

```python
@time_trigger("period(2020/01/01, 10sec)")
async def get_giga_state():
   ...
```

which is logging every 10 seconds:

![image](https://user-images.githubusercontent.com/96162/169376225-1052160b-8ef0-4fed-8f32-bfe52e3bf064.png)

and don't know how to filter out as the entity doesn't seem to be set properly and clicking there does nothing, any idea how I can workaround this?

**Comment by glmnet** [comment]
Figured out:
```
recorder:
  exclude:
      - pyscript.file_airplay_playing_get_giga_state
```

**Comment by VikingGer** [comment]
Having the same issue, not getting it resolved in either way.
Neither by 
recorder:
  exclude:
    entities:
      - pyscript.script

logger:
  default: info
  logs:
    custom_components.pyscript: error
    custom_components.pyscript.file.script.function: error

logbook:
  exclude:
    entities:
      - pyscript.script
    
Tried a lot of things and running out of ideas now. The only way to "mend" the problem a bit is setting the @time_trigger period to a higher value, which is less than optimal.

**Comment by stigvi** [comment]
> Having the same issue, not getting it resolved in either way. Neither by
> 
> ```
> recorder:
>   exclude:
>     entities:
>       - pyscript.script
> 
> logger:
>   default: info
>   logs:
>     custom_components.pyscript: error
>     custom_components.pyscript.file.script.function: error
> 
> logbook:
>   exclude:
>     entities:
>       - pyscript.script
> ```
> 
> Tried a lot of things and running out of ideas now. The only way to "mend" the problem a bit is setting the @time_trigger period to a higher value, which is less than optimal.

For the logbook, try this:

logbook:
  exclude:
    entity_globs:
      - pyscript.*
