### ISSUE TITLE
app :  config type TypeError: string indices must be integers

### ISSUE THREAD

**Issue by kabcasa** [custom-components/pyscript#352]
Could you help please I'm going crazy it's my first app with pyscript .
the state_trigger is ok but when want to use the app I get an error for config :

<2022-05-29 03:36:56 INFO (MainThread) [custom_components.pyscript.global_ctx] Reloaded /config/pyscript/currentgen.py
2022-05-29 03:36:56 INFO (MainThread) [custom_components.pyscript.file.currentgen.currentoff_startup] {'allow_all_imports': True, 'hass_is_global': True, 'apps': {'currentoff': [{'dev': 'dev1', 'switch_id': 'switch.salon_socket_1', 'CTlim': 0.7, 'DTref': 0, 'DDref': 0}, {'dev': 'dev2', 'switch_id': 'switch.salon_socket_1', 'CTlim': 0.5, 'DTref': 30, 'DDref': 10}, {'dev': 'dev3', 'switch_id': 'switch.salon_socket_1', 'CTlim': 0.3, 'DTref': 60, 'DDref': 10}]}}
2022-05-29 03:36:56 INFO (MainThread) [custom_components.pyscript.file.currentgen.currentoff_startup] app allow_all_imports
2022-05-29 03:36:56 INFO (MainThread) [custom_components.pyscript.file.currentgen.currentoff_startup] app hass_is_global
2022-05-29 03:36:56 INFO (MainThread) [custom_components.pyscript.file.currentgen.currentoff_startup] app apps
2022-05-29 03:36:56 ERROR (MainThread) [custom_components.pyscript.file.currentgen.currentoff_startup] Exception in <file.currentgen.currentoff_startup> line 53:
        @state_trigger(f"float(sensor.current) < {config['CTlim']} and {config['switch_id']} == 'on' and vcur == False", state_hold_false=0)
                                                         ^
TypeError: string indices must be integers

@state_trigger(f"float(sensor.current) < {config['CTlim']} and {config['switch_id']} == 'on' and vcur == False", state_hold_false=0)
                                                         ^
TypeError: string indices must be integers >

`###########  the config yaml file :

allow_all_imports: true
hass_is_global: true
apps:
currentoff:
  - dev : dev1
    switch_id: switch.salon_socket_1
    CTlim : 0.7
    DTref : 0
    DDref: 0 
  - dev : dev2
    switch_id: switch.prise2 Socket 1
    CTlim : 0.5
    DTref : 30
    DDref: 10 
  - dev : dev3
    switch_id: switch.hall_socket_1
    CTlim : 0.3
    DTref : 60
    DDref: 10 
        
'''
registered_triggers = []
global_vars = {}

def make_currentoff(config):
    vcur = False #global_vars[f"{config['cur']}"]
 
    @state_trigger(f"float(sensor.current) < {config['CTlim']} and {config['switch_id']} == 'on' and vcur == False", state_hold_false=0)
    def currentoff():
        global global_vars
        dev_id = config["dev"]
        DTref = config["DTref"]
        task.unique(f"currentoff_{dev_id}")
        switch.turn_off(entity_id=config["switch_id"])
        vcur = True #global_vars[f"{config['cur']}"] = True
        task.sleep(float(1))
        vswitch_id = config["switch_id"]
        log.info(f"currentoff etat apres lancer trigger {vswitch_id}")
        if float(DTref) == 0 : return
        
        task.sleep(float(DTref))
        switch.turn_on(entity_id=config["switch_id"])
        task.sleep(float(1))
        log.info(f"currentoff  {vswitch_id}")
        task.sleep(float(config["DDref"]))
        switch.turn_off(entity_id=config["switch_id"])
        vcur = False #global_vars[f"{config['cur']}"] = False
        task.sleep(float(1))
        log.info(f"currentoff  {vswitch_id}")

    registered_triggers.append(currentoff)

@time_trigger('startup')
def currentoff_startup():
    log.info(pyscript.config)
    for app in pyscript.config:
        log.info("app "+app)
        make_currentoff(app)`

**Comment by craigbarratt** [comment]
`pyscript.config` is a `dict`.  In this loop, `app` will be a string (the keys in the `dict`):
```python
for app in pyscript.config:
    log.info("app "+app)
    make_currentoff(app)
```
So the `config` argument to the function will be a string, which then gives the error when you index it with a string.

If you look at the log message, `pyscript.config["apps"]["currentoff"]` is a list of dicts with each of the config parameters.  So you probably want to do this instead:
```python
for dev_config in pyscript.config["apps"]["currentoff"]:
    make_currentoff(dev_config)
```

**Comment by kabcasa** [comment]
That fix the error .Tks
