### ISSUE TITLE
pyscript page shows code instead of executing it

### ISSUE THREAD

**Issue by jpolache** [custom-components/pyscript#354]
I'm using pipenv and installed pyttsx3-2.90-py3-none-any.whl. Browser is Chrome Version 102.0.5005.63. The example file numpy.html works as expected using both the vscode live server and the python http.server, but this code only displays the python code on the web page. The same code executed locally as a python script runs as expected;

````
<!DOCTYPE  @html>
<!-- <html lang="en"> -->
<head>
    <title>TTS server</title>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>    
    <py-env>
        - pyttsx3
    </py-env>
</head>
<body>

    <h1>TTS server</h1>
<div id="tts"></div>
<pyscript output="tts">
import pyttsx3

def main():
    engine = pyttsx3.init()
    rate = engine.getProperty('rate')
    #print (rate)
    engine.setProperty('rate', 125)

    voices = engine.getProperty('voices')
    
    for voice in voices:
        engine.setProperty('voice', voice.id)
        #print(voice.id)
        engine.say('The quick brown fox jumped over the lazy dog.')
        engine.runAndWait()

main():

</pyscript>

</body>
</html>
````

Not sure if this is a bug or a coding error.  
Thanks

![pyscript](https://user-images.githubusercontent.com/10584126/170881967-6ef1519a-28b7-42ad-8d98-6ab257001fd6.png)

**Comment by jpolache** [comment]
Nvmd, forgot the hyphens in <py-script>

**Comment by craigbarratt** [comment]
@dlashua - thanks for pointing that out.  I had no idea what the OP meant...
