### ISSUE TITLE
await wasn't used with future

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#36]
Code:

In a Class:
```python
    def get_unique_id(self):
        return f'occupancy_manager_{self.state_entity}'
```

Error:
```
2020-10-11 06:18:22 ERROR (MainThread) [custom_components.pyscript.apps.occupancy_manager.startup_trigger] Exception in <apps.occupancy_manager.startup_trigger> line 113:
            return f'occupancy_manager_{self.state_entity}'
                                        ^
RuntimeError: await wasn't used with future
```

Please let me know if you need to see more of the class code.

**Comment by dlashua** [comment]
This seems to happen outside of a class as well and happens without the f-string:

```python
def get_unique_id(data):
    log.info(data)
    state_entity = data["state_entity"]
    unique_id = 'occupancy_manager_nocls_' + state_entity
    return unique_id
```

**Comment by dlashua** [comment]
This might seems to happen most often at startup/reload. Perhaps it's some kind of residual from cancelling the running task?

**Comment by craigbarratt** [comment]
I haven't been able to replicate this.  The error reporting by default doesn't give any information about where the error is in the internal code. 

Could you add the following code to `custom_components/pyscript/eval.py` so the error shows the internal traceback too?
```diff
--- a/custom_components/pyscript/eval.py
+++ b/custom_components/pyscript/eval.py
@@ -10,6 +10,7 @@ import io
 import keyword
 import logging
 import sys
+import traceback

 import yaml

@@ -1827,7 +1828,7 @@ class AstEval:
         else:
             mesg = f"Exception in <{self.filename}>:\n"
             mesg += f"{type(exc).__name__}: {exc}"
-        return mesg
+        return mesg + "\n" + traceback.format_exc(-1)

     def get_exception(self):
         """Return the last exception str."""
```

**Comment by dlashua** [comment]
Excellent. I was wondering how to get a more complete traceback!! I'll let you know what I see.

**Comment by dlashua** [comment]
Here's the traceback:

```
2020-10-11 16:50:11 ERROR (MainThread) [custom_components.pyscript.apps.occupancy_manager_nocls.inner_occupied_states] Exception in <apps.occupancy_manager_nocls.inner_occupied_states> line 54:
        return unique_id
               ^
RuntimeError: await wasn't used with future
Traceback (most recent call last):
  File "/config/custom_components/pyscript/function.py", line 125, in task_unique
    await task
RuntimeError: await wasn't used with future
```

**Comment by craigbarratt** [comment]
It's interesting that the immediate prior line 124, `task.cancel`, doesn't given an error, but the `await` does.

Who calls `kill_others` (ie, from a trigger function, or script, or jupyter interactive)?   Is reload involved here?  

If we catch that error, it would be interesting to see what `task` is when it fails.  Here's a few lines of code that does that:
```diff
--- a/custom_components/pyscript/function.py
+++ b/custom_components/pyscript/function.py
@@ -125,6 +125,11 @@ class Function:
                             await task
                         except asyncio.CancelledError:
                             pass
+                        except Exception as exc:
+                            _LOGGER.error("task_cancel: exception with task = %s, our_tasks = %s: %s, unique_name2task = %s: %s",
+                                           task, cls.our_tasks, cls.unique_name2task, traceback.format_exc(-1))
+                            raise(exc)
+
             task = asyncio.current_task()
             if task in cls.our_tasks:
                 cls.unique_name2task[name] = task
```

**Comment by dlashua** [comment]
`kill_others` is called, essentially, by a state_trigger function.

You can see the (not so clean, yet) code here:

https://gist.github.com/dlashua/db9a5ebc8c676bfe4564036ef7d60f0f

(This was originally a Class, but I changed it to this non-class version in order to make sure the Class issues weren't causing my problems).

**Comment by dlashua** [comment]
also, in that code, you can see that `kill_others()` is no longer using `task.unique(get_unique_id(name))`. I moved the call to `get_unique_id` into a separate line (based on the traceback and a hunch) and I've yet to see the error again.

I'm going to add this extra tracing code and put it back to all being on one line to see if I can catch it with a full trace.

**Comment by dlashua** [comment]
Ever since my restart, with this additional trace reporting, it hasn't occurred.

That being said, the code I shared is still quite broken, and I can't figure out why. 

Sometimes, the `log.info()` after `task.sleep()` will indicate that it did not sleep for the full time requested. However, other times, within a few seconds of starting the delay, it'll indicate that it slept the full time. I think there's a second issue compounding the situation. The code relies heavily on `task.unique()` to kill the task that is running `task.sleep()`. I rewrote the code and ripped out all use of `task.sleep` and `task.unique`. Yet, until I restarted Home Assistant, I still saw the old sleep code triggering in the logs. So I think I had a lot of tasks running in the background either as a result of a bug in `task.unique()` or a bug in my code. I rewrote it like this:

```python
off_triggers = {}
data = {}

def set_off_trigger(name, seconds, force=False):
    if force:
        clear_off_trigger()

    if name in off_triggers:
        log.info(f'{name}: delayed off already set')
        return

    log.info(f'{name}: pending_off')
    data[name]["state"] = 'pending_off'
    data[name]['delay_off_start'] = time.time()
    log.info(f'{name}: delay off in {seconds} seconds')

    end_datetime_iso = (datetime.datetime.now() + datetime.timedelta(seconds=seconds)).strftime('%Y/%m/%d %H:%M:%S.%f')

    log.info(f'{name}: will turn off at {end_datetime_iso}')

    @time_trigger(f'once({end_datetime_iso})')
    def do_off():
        clear_off_trigger(name)
        elapsed = round(time.time() - data[name]['delay_off_start'], 2)
        log.info(f'{name}: delay elapsed in {elapsed}/{seconds} seconds')
        turn_off(name, immediate=True)

    off_triggers[name] = do_off

def clear_off_trigger(name):
    if name in off_triggers:
        log.info(f'{name}: clearing delayed off')
        del off_triggers[name]
```

... using a `time_trigger` set to the moment the delay should expire, and deleting the function reference when I want to cancel the delay.

So far, this is working well. The only issue I found was that, if I use a VERY short delay, sometimes, by the time it's fully registered, it's in the past. pyscript doesn't complain about this, but it also never triggers.

**Comment by craigbarratt** [comment]
Ok, thanks for the examples. From the symptoms it looks like a mixup in execution contexts. In thinking about it more, I just realized a place where that can happen - when there are multiple instances of a trigger function running concurrently.

Let me work on a fix for that.

**Comment by craigbarratt** [comment]
Pushed potential fix da3e252.  Passes tests, but no other testing done yet.

**Comment by dlashua** [comment]
I've updated to the latest master, and altered my code to work with `task.sleep()` again. It seems to be working better, but I'm still seeing this error in my logs. I've updated the gist so you can see the current code:

https://gist.github.com/dlashua/db9a5ebc8c676bfe4564036ef7d60f0f

Line 120 produces the first line of these logs.
turn_off() is called.
Line 168 produces the second line of logs.
clear_delayed_off() is called.
Line 151 produces the third line of logs.
And then line 152 (`task.unique()`) is ultimately what leads to the exception.

```
2020-10-12 07:45:23 INFO (MainThread) [custom_components.pyscript.apps.occupancy_manager_nocls.inner_state_trigger] input_boolean.bathguest_occupied: delay elapsed in 300.0/300 seconds (sleep)
2020-10-12 07:45:23 INFO (MainThread) [custom_components.pyscript.apps.occupancy_manager_nocls.inner_state_trigger] input_boolean.bathguest_occupied: immediate off
2020-10-12 07:45:23 INFO (MainThread) [custom_components.pyscript.apps.occupancy_manager_nocls.inner_state_trigger] input_boolean.bathguest_occupied: clearing delayed off by killing others (sleep)
2020-10-12 07:45:23 ERROR (MainThread) [custom_components.pyscript.apps.occupancy_manager_nocls.inner_state_trigger] Exception in <apps.occupancy_manager_nocls.inner_state_trigger> line 54:
        return unique_id
               ^
RuntimeError: await wasn't used with future
```

**Comment by dlashua** [comment]
Also worth noting... despite these triggers turning on and off with intended delays several times since I updated... this Exception has only happened once.

Is it possible that the Exception is happening in the task that is being killed? I think it must be because, assuming the Exception would halt execution in that chain of code, the input boolean should not have turned off after the Exception was seen, but it did.

**Comment by dlashua** [comment]
this exception is not occurring any more. on top of that, all of the `task.sleep()` and `task.unique()` seem to be working correctly.

I'll close this and reopen with more information if the issue presents again.
