### ISSUE TITLE
ModuleNotFoundError:  Modules not loading in new home assistant?

### ISSUE THREAD

**Issue by spalt** [custom-components/pyscript#370]
Not sure if this is a "them" issue or not but in the newest HA that I believe I upgraded to the other day, I am getting 

ModuleNotFoundError: No module named 'bluepy'

This worked fine before the upgrade...

Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest

**Comment by wigster** [comment]
Look in the Bluetooth breaking changes here in the 2022.7 release notes:

https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes

bluepy is no longer supported.

**Comment by spalt** [comment]
Thanks
