### ISSUE TITLE
When state_hold != None then kwargs will not be set

### ISSUE THREAD

**Issue by jkrasinger** [custom-components/pyscript#374]
pyscript Version 1.3.3
homeassistant Version 2022.6.7 on hassio on Raspberry Pi

When i set state_hold to a value != None, then kwargs will not be set correctly in a @state_trigger.

Correct: The following state_trigger with state_hold=None set "status=min" on triggering:
```@state_trigger(f"float({t_sensor}) < float({i_min_day})", state_hold_false=0, state_hold=None, state_check_now=True, kwargs={'status': 'min'})``` 

Wrong: The following state_trigger with state_hold=60 set "status=None" on triggering:
```@state_trigger(f"float({t_sensor}) < float({i_min_day})", state_hold_false=0, state_hold=60, state_check_now=True, kwargs={'status': 'min'})```

**Comment by ALERTua** [comment]
i support this issue. this bugs me a lot.

**Comment by absolutezer093** [comment]
This is affecting me as well

**Comment by ALERTua** [comment]
I've finally got some time to work on this issue and found a fix. #382
