### ISSUE TITLE
pyscript jupyter kernel in juypter-lite addon

### ISSUE THREAD

**Issue by iot49** [custom-components/pyscript#379]
HA has a Jupyter addon (jupyter lite) that can run the `pyscript` kernel right from within HA.

One complication is the location of `pyscript.conf` which is overwritten whenever the docker container is refreshed. Each time `pyscript.conf` is lost and needs to be recreated!

Changing the location of `pyscript.conf` to somewhere `/config` (e.g. in `/config/notebooks`) would avoid this issue. Possibly a configuration variable could be added to set a custom location for `pyscript.conf`.

Thank you for your consideration!

**Comment by MizterB** [comment]
While I'd also like to see a more out-of-the-box experience, you can get this working by adding `init_commands` to the add-on config.  

Set up your `pyscript.conf` in `/config/notebooks/` and configure as follows:

```
init_commands:
  - pip install hass_pyscript_kernel
  - jupyter pyscript install
  - >-
    ln -fs /config/notebooks/pyscript.conf
    /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
```

**Comment by iot49** [comment]
But isn't then the link (not file) still subject to clobbering when the container reloads or updates?
Anyway, for this and other reasons I decided to drop HassOS and instead run my own dockers. Now it's fully configurable.

**Comment by MizterB** [comment]
For anyone else reading this...the answer to the above question is "no".  By adding the `init_commands` shown above, the kernel shim and link to the config file are restored every time the container is rebuilt or updated.
