### ISSUE TITLE
unknown msg_type: comm_open [HA version 2022.8.7, integration v.1.3.3]

### ISSUE THREAD

**Issue by tms320** [custom-components/pyscript#390]
I have installed ["HASS Pyscript kernel shim for Jupyter"](https://github.com/craigbarratt/hass-pyscript-jupyter) on my Windows client machine.
If I create new hass pyscript in web interface:
![image](https://user-images.githubusercontent.com/24802646/189979599-539c0a28-e6e2-4ff5-a22d-5baba77dfe4a.png)
I see the following error(s) in the HA logs:
![image](https://user-images.githubusercontent.com/24802646/189979689-173b6373-1a1a-4ddb-84ce-d832f91a2e2e.png)
What does it mean?
PS: I am new with Python & Jupyter

**Comment by tms320** [comment]
The problem still exists ((

**Comment by craigbarratt** [comment]
Ok, I see those too.  Just to confirm - does jupyter still run correctly?

**Comment by craigbarratt** [comment]
I pushed 31fc51e to ignore these messages - they are not needed.

**Comment by tms320** [comment]
> Ok, I see those too. Just to confirm - does jupyter still run correctly?

Yes, it runs correctly )
