### ISSUE TITLE
'StateVal' object has no attribute 'old'

### ISSUE THREAD

**Issue by ALERTua** [custom-components/pyscript#394]
I'm trying to receive a notification on 'sensor.hacs' value raise only, rather than lower and raise, and I came up with unexpected behavior.
In case you don't know what 'sensor.hacs' is, this sensor indicates the total number of HACS updates available, so if a new update appears, it goes up, and when you install one of them, it goes down.
```
@state_trigger(int(sensor.hacs) > int(sensor.hacs.old), state_check_now=True)
```
Results in
```
int(sensor.hacs) > int(sensor.hacs.old)
                       ^
AttributeError: 'StateVal' object has no attribute 'old'
```
but the documentation states that .old can be used and only results in None if the .old hasn't yet been filled.

**Comment by craigbarratt** [comment]
You are missing quotes around the `@state_trigger` argument: it needs to be a string:
```python
@state_trigger("int(sensor.hacs) > int(sensor.hacs.old)", state_check_now=True)
```

**Comment by ALERTua** [comment]
my bad. thank you
my workaround was:
```
ENTITY_ID = 'sensor.hacs'

@state_trigger(ENTITY_ID)
def func_sensor_hacs(trigger_type=None, var_name=None, value=None, old_value=None, context=None, **kwargs):
    try:
        trigger = int(value) > int(old_value)
    except:
        trigger = False

    if trigger:
        friendly_name = tools.friendly_name(var_name)
        tools.telegram_message(f'{friendly_name}⬆️{value}', disable_notification=True)
```
