### ISSUE TITLE
state.get() function does not work within a @state_trigger

### ISSUE THREAD

**Issue by elearningdienst** [custom-components/pyscript#409]
Hi Folks,

I'm trying to automate my living space ventilation and have a problem with getting state variables within a @state_trigger

That is my code, it works generally as expected:

```
Status = state.get('switch.aus'), state.get('switch.tasmota_ac0bfbd9e600_switch_relay_3'), state.get('switch.tag'), state.get('switch.party') 
Status
```
The output is ```('off', 'off', 'on', 'off')```, which is the expeted state of the relais module in the working condition, right now.

Once I put it in a @state_trigger statement, it doesn't work anymore:

```
@state_trigger('float(sensor.wohnung_co2) >= 1000 or float(sensor.lywsd03mmc_atc_hum) >= 60 or float(sensor.thx1_w230150x_hum_7) >= 60', watch='switch.aus, switch.tasmota_ac0bfbd9e600_switch_relay_3, switch.tag, switch.party')

     Status = state.get('switch.aus'), state.get('switch.tasmota_ac0bfbd9e600_switch_relay_3'), state.get('switch.tag'), state.get('switch.party') 
     Status
```
The output is:

```
Exception in <jupyter_26> line 2:
        Status = state.get('switch.aus'), state.get('switch.tasmota_ac0bfbd9e600_switch_relay_3'), state.get('switch.tag'), state.get('switch.party') 
       ^
IndentationError: unexpected indent (jupyter_26, line 2)
```

Where is my mistake? I use the watch-statement with the needed entities as suggested in the documentation. Any ideas? 

I develop in Jupyter Notebook with pyscript kernel.

**Comment by craigbarratt** [comment]
A decorator like `@state_trigger` must appear immediately before a function declaration.  So you need to declare a function, and put the `Status` statement inside that function.

**Comment by craigbarratt** [comment]
Something like this:
```python
@state_trigger('float(sensor.wohnung_co2) >= 1000 or float(sensor.lywsd03mmc_atc_hum) >= 60 or float(sensor.thx1_w230150x_hum_7) >= 60', watch='switch.aus, switch.tasmota_ac0bfbd9e600_switch_relay_3, switch.tag, switch.party')
def trigger_func():
     Status = state.get('switch.aus'), state.get('switch.tasmota_ac0bfbd9e600_switch_relay_3'), state.get('switch.tag'), state.get('switch.party') 
     Status
```

**Comment by elearningdienst** [comment]
Thanks for helping a dummie ;-)

Works, so my my living space ventilation is now soewhat smart.
