### ISSUE TITLE
@event_trigger : event_type (first parameter) cannot be longer than 8 ??)

### ISSUE THREAD

**Issue by stefanuytterhoeven** [custom-components/pyscript#417]
```python
registered_triggers = list()

def create_event_trigger():
    @event_trigger("my_event1")
    def got_my_event(**kwargs):
        log.info(f"got my_event: kwargs={kwargs}")
    registered_triggers.append(got_my_event)



@time_trigger('startup')
def event_default_startup():
    create_event_trigger()
    event.fire("my_event1", my_param1=100, fruit="apple")
```

this doesn't work. It's almost the same as one of the examples.
when the event_type is "my_event", then it works. Apparenty, the event_type cannot be longer than 8 characters?
when I look in "developers utilties", and listen for "my_event1", it let me see that de event is fired. So, firing the event is no problem.
But, the      @event_trigger doesn't pick up an event type longer than 8 characters

**Comment by craigbarratt** [comment]
What is your workflow?  Are you running this code in a single jupyter block?  Or is this code in a .py file?

**Comment by stefanuytterhoeven** [comment]
I had a problem with the event trigger. So.i created a new py file with the above statements.
When I name the event_type 'my_event', it just works. The entire trigger is triggered.
When I do the same, with event_type 'my_event1'
Or any name longer than 8 characters, the event trigger is not triggered.
I can see in home assistant that the event is fired.
( I don't use Jupiter)

**Comment by craigbarratt** [comment]
I'm sure this isn't an issue with the length of the event name.

`pyscript` doesn't enable triggers until after the script is completely loaded (eg, run).  So the `event.fire` happens before the event trigger is armed, which means it is missed.

Here's a modified version that fires the event 0.2 seconds after the script runs:
```python
@event_trigger("my_event_long_name_1")
def got_my_event(**kwargs):
    log.info(f"got my_event: kwargs={kwargs}")

def delay_event_fire():
    task.sleep(0.2)
    event.fire("my_event_long_name_1", my_param1=100, fruit="apple")

task.create(delay_event_fire)
```

**Comment by stefanuytterhoeven** [comment]
I will test this one of this days. I did something similar.... Don't understand why it didn't work. I'll let you know the result

**Comment by stefanuytterhoeven** [comment]
Yes, seems to work. 
added a task.sleep after my create_event_trigger, and then it seems to work.
Did that during testing too.... Anyway, I'll add the delay in my code...
Thanks you very much for your time. 
and... happy new year ! :)

**Comment by stefanuytterhoeven** [comment]
Thanks, a delay solved it.
