### ISSUE TITLE
Enhancement request: wildcards in @state_trigger

### ISSUE THREAD

**Issue by fovea1959** [custom-components/pyscript#420]
Can `@state_trigger` be changed to support wildcards?

I am wanting to do:
````
@state_trigger('sensor.ble_temperature_*')
````

**Comment by fovea1959** [comment]
Not needed; can be done with trigger closures.

**Comment by craigbarratt** [comment]
You can also do this without closures:
```python
watch_var = ["pyscript.var1", "pyscript.var2", "pyscript.var3"]
@state_trigger("True", watch=watch_var)
def got_change(**kwargs):
    log.info(f"got change {kwargs}")
```
This is telling it to always trigger whenever any of the watch variables change.

**Comment by craigbarratt** [comment]
This alternative also works if you use the latest github code (just did commit 5058fed to fix the expansion of *list in decorator function arguments):
```python
watch_var = ["pyscript.var1", "pyscript.var2", "pyscript.var3"]
@state_trigger(*watch_var)
def got_change(**kwargs):
    log.info(f"got change {kwargs}")
```
