### ISSUE TITLE
can somone help me run this py script 

### ISSUE THREAD

**Issue by itsboo07** [custom-components/pyscript#421]
Hi i would like to run this pyscript in ha. i cant make it work. can somone help me
```
import cfscrape
import requests
from bs4 import BeautifulSoup

# Use cfscrape to bypass Cloudflare protection
scraper = cfscrape.create_scraper()

# Send a GET request to the website
response = scraper.get("https://robu.in/product/spx3819m5-l-3-3-tr-500ma-low-noise-ldo-voltage-regulator-5-pin-sot-23/")

# Parse the HTML content
soup = BeautifulSoup(response.content, "html.parser")

# Find the element containing the availability information
availability_element = soup.find("p", class_="stock in-stock")
availability_element1 = soup.find("p", class_="stock out-of-stock")

# Extract the availability information
if availability_element:
    availability = availability_element.text
    print(f"Availability: {availability}")
elif availability_element1:
    availability1 = availability_element1.text
    print(f"Availability: {availability1}")

```

**Comment by craigbarratt** [comment]
Could you describe the error or problem you are seeing?

One issue: you will need to use `aiocfscrape` instead of `cfscrape` to avoid blocking I/O.

**Comment by itsboo07** [comment]
sorry my bad. I saved this script in home assistant under config/pyscript/ but the script is not showing up in call service.

**Comment by craigbarratt** [comment]
For it to show up as a service you need to define a function with the code you want to execute, and precede the function definition with the `@service` decorator.

As I mentioned, you'll also need to use `aiocfscrape` instead `cfscrape`.
