### ISSUE TITLE
Not available under intergrations? 

### ISSUE THREAD

**Issue by TomKranenburg** [custom-components/pyscript#435]
Is this project dead? There is nothing in Home assistant integrations called pyscript anymore.

**Comment by ALERTua** [comment]
![image](https://user-images.githubusercontent.com/8375129/218790926-75728260-da81-4780-aaf1-6022653ba4ca.png)

**Comment by craigbarratt** [comment]
Thanks @ALERTua  - I tested a new Hass/HACS install, and pyscript appears when you search for it.
