### ISSUE TITLE
assignment operator yields wrong value

### ISSUE THREAD

**Issue by Kaptensanders** [custom-components/pyscript#438]
Hi, first of all, thanks for pypscript, it's just awsome.

When doing this:
```
a = None or "foo" 
```
a is incorrectly assigned the value `None`

however, when used in a function decorated with `@pyscript_compile`, the expression yields the expected behavior `a="foo"`

Pyscript:   1.3.3
Home Assistant Core installation: 2023.2.2
Python 3.10.9

Br Anders

**Comment by craigbarratt** [comment]
Yikes - thanks for reporting.  I've pushed fix f77d859 and test cases 48b6a8f.
