### ISSUE TITLE
failling to get debug in log file

### ISSUE THREAD

**Issue by dominig** [custom-components/pyscript#448]
I have a script name roudrobin.py in the pyscript directory.
I cannot get log at debug or info level just for that script.
from the documentation and forum I understand that the two following config should work but nothing does it. 
Is the documentation in line with latest release ? Where do I get it wrong ?
Is a full reboot the only way to change log level avec changing config.yaml

------------ from documentation -------
logger:
  default: critial
  logs:
     custom_components.pyscript.file.roundrobin: debug

-------------- from forum -------------------
logger:
  default: critial
  logs:
     custom_components.pyscript: debug

**Comment by craigbarratt** [comment]
Those forms should work.  I'm not sure when/whether HASS will reload its configuration file.  Have you tried restarting HASS?

BTW, github issues are for reporting bugs or feature requests.  These topics are more appropriate for discussions.

**Comment by dominig** [comment]
I am afraid that it might just a documentation error. If you follow the documentation and have a file name roundrobin.py
you debug configuration should be:
  custom_components.pyscript.file.roundrobin: debug

 The .py is clearly out in the documentation as you can see in the attached screenshot.
![Screenshot_20230312_195749](https://user-images.githubusercontent.com/1193120/224566618-94c865fd-cb2f-4bb0-a87e-98a36f4cd6ab.png)

To be honest I have tried several option and I could not get it to work.
It would be nice to know from the documentation how to get debug operational including understanding what needs reload to get the new config active.

**Comment by craigbarratt** [comment]
Setting logging levels for `pyscript` files and functions works correctly.  I just tested it again.

If you are using Jupyter or VSC, you can set the logging levels by calling the `logger.set_level` service, eg:
```python
logger.set_level(**{"custom_components.pyscript.file.my_script": "debug"})
```
will change the log level for the `my_script.py` script to `debug`.

Alternatively, you can use the HASS UI Developer Tools  to call the `logger.set_level` service with the logging paths you want to change.

**Comment by ALERTua** [comment]
@dominig could you please update or close the issue? Thank you
