### ISSUE TITLE
Feature Request: access to sunset/sunrise in function

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#46]
This works, but it's complicated to write and follow:
```python
@state_trigger('binary_sensor.dark == "on"')
@time_active("range(sunrise - 120min, sunset + 120min)")
def turn_on_dark():
    turn_on()

@state_trigger('binary_sensor.downstairs_occupied == "on" and binary_sensor.dark == "on"')
def turn_on_occupied():
    turn_on()

@state_trigger('binary_sensor.downstairs_occupied == "off"')
@time_active("range(sunset + 120min, sunrise - 120min)")
def turn_off_notoccupied():
    turn_off()

@state_trigger('binary_sensor.dark == "off"')
def turn_off_notdark():
    turn_off()

@time_trigger('startup')
@state_active('binary_sensor.dark == "on"')
@time_active("range(sunrise - 120min, sunset + 120min)")
def turn_on_startup_dark():
    turn_on()

@time_trigger('startup')
@state_active('binary_sensor.downstairs_occupied == "on" and binary_sensor.dark == "on"')
def turn_on_startup_occupied():
    turn_on()

@time_trigger('startup')
@state_active('binary_sensor.downstairs_occupied == "off"')
@time_active("range(sunset + 120min, sunrise - 120min)")
def turn_off_startup_notoccupied():
    turn_off()

@time_trigger('startup')
@state_active('binary_sensor.dark == "off"')
def turn_off_startup_notdark():
    turn_off()
```

I would prefer this:
```python
import datetime

@time_trigger('startup')
@state_trigger('True or binary_sensor.dark or binary_sensor.downstairs_occupied')
def set_lights():
    today = datetime.datetime.today()
    start_time = today.replace(hour=5, minute=0) # would like sunrise - 120min
    end_time = today.replace(hour=22, minute=0) # would like sunset + 120min

    if binary_sensor.dark == "off":
        turn_off()
        return

    if start_time < datetime.datetime.now() < end_time:
        turn_on()
        return

    if binary_sensor.downstairs_occupied == "on":
        turn_on()
        return

    turn_off()
```

However, as you can see in the code comments, there's not an easy way to get to sunrise/sunset offsets.

**Comment by craigbarratt** [comment]
Here's a way to get sunrise and sunset.  This requires the `tzlocal` package to be installed.  Unfortunately I can't see a better way to get the local timezone; it's in `hass.config.time_zone` but that's not exposed in pyscript.  It would make sense for the `zone.home` component to expose it.
```python
import astral
import datetime
from tzlocal import get_localzone

here = astral.Location(("", "", zone.home.latitude, zone.home.longitude, str(get_localzone()), 0))
sunrise = here.sunrise(datetime.datetime.today()).replace(tzinfo=None)
sunset = here.sunset(datetime.datetime.today()).replace(tzinfo=None)
print(f"sunrise was {(datetime.datetime.now() - sunrise).total_seconds() / 3600:.2f} hours ago")
```

**Comment by dlashua** [comment]
Thanks! This worked perfectly.

It would make sense for `zone.home` to expose time_zone. However, there are other useful things in `hass.config` (like preferred units of measurement, elevation, long/lat (also available in zone.home), location_name, installed components, and HASS url). Perhaps pyscript should expose this as `pyscript.hass_config`?

**Comment by craigbarratt** [comment]
Yes, that could make sense. I was also wondering whether I should just expose `hass`?  Maybe that's too risky.

Or perhaps I should expose `hass.config` as `pyscript.hass.config` or simply `hass.config`, which leaves open the possibility of exposing other `hass` objects as needed later?

**Comment by dlashua** [comment]
I, personally, wouldn't mind if all of `hass` was exposed somewhere. Even if it was undocumented. Having that kind of access can certainly break an installation, but, it can also provide the tools for some great ideas that end up being pyscript features eventually.

I like the idea of exposing it as `hass.config` leaving other options open for the future. And either exposing all of `hass` as `hass` or, if you'd prefer to hide it and leave it undocumented, under some other name -- `hass_raw` perhaps.

**Comment by fleXible** [comment]
@dlashua why not just use the attributes of the entity **sun.sun** and its attributes?
It's active by default, check the docs [integrations/sun](https://www.home-assistant.io/integrations/sun/)
To calculate the needed offsets, use **datetime.timedelta**

**Comment by dlashua** [comment]
@fleXible that's a good idea. I'll give it a shot. Thanks!

**Comment by bdeluca** [comment]
I am leaving this here for others, this will give the local timezone. 
`datetime.datetime.now(datetime.timezone.utc).astimezone().tzinfo`

**Comment by ALERTua** [comment]
An alternative way to access datetime object via pyscript:
```
config = hass.config
timezone_str = config.time_zone

import homeassistant.helpers.template as template
now = template.now(hass)
now_utc = template.utcnow(hass)
timestamp = now.timestamp()
```
via https://github.com/ALERTua/ha_pyscript_modules/blob/main/entities/ha.py
