### ISSUE TITLE
The declaration of the path of the scripts in the configuration.yaml does not work anymore ?

### ISSUE THREAD

**Issue by mcpfr** [custom-components/pyscript#463]
Hello,

Following the update to version 1.4.0 (H.A 2023.2.5), my scripts no longer worked. I had to move them in /config/pyscript while I have in the configuration.yaml the following line:

pyscript: !include xxxxx/pyscript/_configuration.yaml

Is this feature no longer supported?

Thanks

**Comment by craigbarratt** [comment]
I'm not aware of any changes in 1.4.0 that should affect that.  `pyscript` gets the script folder by calling `hass.config.path("pyscript")`. Also,  I believe the config includes are handled by HASS.

**Comment by mcpfr** [comment]
Hello, 

Thanks for your answer.

**Comment by mcpfr** [comment]
I have modified my configuration.yaml: 
add line: pyscript: !include xxxxx/pyscript/_configuration.yaml

After restarted HA,  hass.config.path("pyscript") retour always "/config/pyscript"

.....

**Comment by craigbarratt** [comment]
I would expect that `hass.config.path("pyscript")` always has returned "/config/pyscript".

Did you use symlinks or some other mechanism to put your scripts in a different directory?  Perhaps some recent upgrade removed or replaced those symlinks.  Just a guess though.

**Comment by mcpfr** [comment]
Hello,

Thanks, but i have not modified another elements in my config.

I search ... modifications

**Comment by mcpfr** [comment]
It's my fault !
I reread my notes....
I had modified the "FOLDER" content in the const.py file, to indicate another directory, and I had not reported this modification after the update to 1.4.0

Sorry and thank you for your help
