### ISSUE TITLE
(False or False) == 0 ?

### ISSUE THREAD

**Issue by redlefloh** [custom-components/pyscript#469]
This should probably not be the case? Or am I missing something? 
 
<img width="316" alt="Screenshot 2023-05-18 at 15 54 08" src="https://github.com/custom-components/pyscript/assets/24863182/1a274c23-19f9-4c92-b492-2e04d0a72dfe">

(this is with pyscript 1.4.0)

**Comment by craigbarratt** [comment]
Definitely a bug.  I pushed a fix 58e2c26.

**Comment by craigbarratt** [comment]
Released in 1.5.0.
