### ISSUE TITLE
Is pyscript ready for Python 3.11?

### ISSUE THREAD

**Issue by bjornbak** [custom-components/pyscript#471]
Home Assistant 2023.6 is coming up which features an upgrade to Python 3.11.

Not sure what that entails other than is is supposedly faster...

Just want to call out if pyscript is ready for the upgrade?

**Comment by craigbarratt** [comment]
I pushed commits 4ddfefc and 3225f41, which upgrade the tests to Python 3.11.  I don't think any significant core code changed (just tests and test requirement versions), so the current release should be ok.  However, I still need to actually test it with the latest beta release.

**Comment by bjornbak** [comment]
Fantastic!

**Comment by craigbarratt** [comment]
Yes, the 1.5.0 release uses Python 3.11.
