### ISSUE TITLE
Match statement

### ISSUE THREAD

**Issue by stefanuytterhoeven** [custom-components/pyscript#479]
first of all, I'm no expert in Python.

but, from what I've read, the match/case statement should be supported as of version 3.10 of python.

In HA, we are at 3.11 now. When retrieving the python version in pyscript it says 3.11

So, when I try to use match/case like

```
testvar='value'
match testvar:
     case 'value': 
          pass
      case _: 
          pass
```

this gives me error:
NotImplementedError: ..... not implemented ast ast_match

**Comment by craigbarratt** [comment]
`Pyscript` implements a python interpreter using async methods.  I wasn't aware this language feature was added, so I'll need to add support for it.

**Comment by craigbarratt** [comment]
I reviewed [PEP 636](https://peps.python.org/pep-0636/) and it looks quite difficult to implement in the `pyscript` interpreter.  So I'm not planning to support this.

I'd recommend putting your `match` code in a function with the `@pyscript_compile` decorator.  That way you'll have access to full native Python functionality inside that function.

**Comment by stefanuytterhoeven** [comment]
Thx!

**Comment by ALERTua** [comment]
@stefanuytterhoeven could you please update or close the issue? Thank you

**Comment by stefanuytterhoeven** [comment]
Solved
