### ISSUE TITLE
"pyscripy not found" error

### ISSUE THREAD

**Issue by kicker10BOG** [custom-components/pyscript#514]
On Home Assistant 2023.8.x, I get this error. 

`homeassistant.loader.IntegrationNotFound: Integration 'pyscripy' not found`

And yes, it says "pyscripy" instead of "pyscript" and I'm running pyscript 1.5.0 after uninstalling it and re-installing it.

**Comment by craigbarratt** [comment]
How did you install it?  What directories are in your `config/custom_components` directory?

**Comment by kicker10BOG** [comment]
I'm using HACS to manage its installation. I just tried commenting out 

```pyscript:
allow_all_imports: true```

and now it seems ok. Did I just miss where that no longer is needed for importing libraries?

**Comment by kicker10BOG** [comment]
Ok, nevermind. I got it working now. I'm not sure what exactly fixed it, but it's all working now with that no longer commented out.
