### ISSUE TITLE
Cron expression dont work

### ISSUE THREAD

**Issue by Acidzero2020** [custom-components/pyscript#515]
I tried this cron expression and it does not work.
```
@time_trigger("cron(*/5 * * 8-1 *)")
[custom_components.pyscript.trigger] Invalid cron expression: <re.Match object; span=(0, 19), match='cron(*/5 * * 8-1 *)'>

```
If the month goes over 12, e.g. from October to January, it does not recognize that. 
If you enter the months one by one, it works without problems.
`@time_trigger("cron(*/5 * * 8,9,10,11,12,1,2,3 *)")`
or 
`@time_trigger("cron(*/5 * * 8-12,1-3 *)")`
works too.

**Comment by craigbarratt** [comment]
`pyscript` uses [`croniter`](https://pypi.org/project/croniter/).  I don't think it supports wrapping of field ranges, and I'm not aware of any implementations that do so.
