### ISSUE TITLE
@event_trigger decorator with 3 arguments 

### ISSUE THREAD

**Issue by marshalltech81** [custom-components/pyscript#519]
Following the documentation https://hacs-pyscript.readthedocs.io/en/latest/reference.html#event-trigger, it looks like the @event_decorator trigger accepts up to 3 arguments where the 3rd argument is the kwarg.  However in attempting to do this, I receive an error that states `decorator @event_trigger got 3 arguments, expected 1 or 2`.

**Comment by craigbarratt** [comment]
Fixed with 8b3f4d8.
