### ISSUE TITLE
Feature request: debounce decorator

### ISSUE THREAD

**Issue by phha** [custom-components/pyscript#54]
Sometimes you will want to limit triggers to a specific frequency. Therefore I would like to suggest a decorator that provides this functionality. 

It would be similar to the existing @time_active decorator, only it would check the time elapsed since the last time a task was called. If that time exceeds a provided threshold, the task is called. Otherwise it is skipped.

Something like this:
```python
@state_trigger('some condition')
@debounce(millis=300)
def some_task():
    pass
```

Meaning that the task will only be exceuted if the last execution was more than 300ms ago.

I tried implementing this myself, only to find out that pyscript doesn't support decorators.

**Comment by craigbarratt** [comment]
Yes, pyscript doesn't support decorators yet, other than the built-in ones.

I added a `hold_off` optional argument to `@time_active`, and `@time_active` is now allowed to take zero arguments. The commit is ae5b172.  Please try the master version to try it out, and the docs should be updated [here](https://hacs-pyscript.readthedocs.io/en/latest/reference.html#time-active).

**Comment by phha** [comment]
That was quick, many thanks!

I tried it and it works fine.

**Comment by craigbarratt** [comment]
Cool.  I also need to add a `duration` optional parameter to `@state_trigger` so that the trigger only happens after the state condition remains true for that amount of time, similar to AppDaemon.

**Comment by dlashua** [comment]
> Cool. I also need to add a `duration` optional parameter to `@state_trigger` so that the trigger only happens after the state condition remains true for that amount of time, similar to AppDaemon.

YES!! Thank you! I'd just finished writing a method to do just this, too! But it's much more elegant built in.

**Comment by dlashua** [comment]
Perhaps you could also consider adding "duration" to `task.wait_until`. This way, at some point in my code I can "wait until binary_sensor.test has been on for 4 minutes starting right now" by doing:

```python
task.wait_until(state_trigger="binary_sensor.test == 'on'", state_check_now=True, duration=4 * 60)
```

**Comment by craigbarratt** [comment]
Yes, when I get around to it, I'll add it to `task.wait_until` too.  However, we'll need a better name than just `duration`, since it's pretty ambiguous for `task.wait_until`.  Maybe `state_duration` or `state_hold`, or ...?

**Comment by craigbarratt** [comment]
Added `state_hold` to `@state_trigger` and `task.wait_until()` 1a7b665

**Comment by dlashua** [comment]
I'll test these tomorrow. THANK YOU!
