### ISSUE TITLE
TypeError: 'EvalFuncVar' object is not callable with Voluptuous

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#55]
This code:

```python
import voluptuous as vol

class IntOrError:
    def __init__(self):
        pass

    def __call__(self, x):
        if isinstance(x, int):
            return x
        raise Exception('Not an int')

SCHEMA = vol.Schema({
    vol.Required('a'): IntOrError(),
    vol.Required('b'): int,
})


def configme(config):
    config = SCHEMA(config)
    doprint(config)


def doprint(x):
    try:
        log.info(x)
    except:
        print(x)


configme({
    "a": 1,
    "b": 2,
})
```

Produces this error:
```
2020-10-24 08:28:50 ERROR (MainThread) [custom_components.pyscript.file.broken] Exception in </config/pyscript/broken.py> line 19:
        config = SCHEMA(config)
                        ^
TypeError: 'EvalFuncVar' object is not callable
```

I tried adding `__call__` to `EvalFuncVar` (just duplicating the existing `call` method). But that results in the passing of a coroutine.

I've also tried writing the IntOrError class as a method and as a lambda, with the same results.

**Comment by craigbarratt** [comment]
Unfortunately native python (eg, `voluptuous`) can't call pyscript functions.  I've been thinking about how to do this, but the challenge is calling the pyscript function requires a pyscript execution context, and there's no general way to pass along via the native python code.  There are some ways to solve this, but I haven't yet figured out a good solution.

A workaround for now is to put the argument checking into a native python module in, eg, `config/pyscript_modules`.  See [this documentation](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#importing).

**Comment by dlashua** [comment]
Ah, okay. I'll figure out a work around.
