### ISSUE TITLE
Even with supports_response, service is not returning anything

### ISSUE THREAD

**Issue by hnykda** [custom-components/pyscript#560]
Hi. Thanks for an awesome lib!

I have a trouble with returning values from my custom services. I read in the docs that `supports_response="only"` should return whatever dict I return in the func, but it simply doesn't return anything when I call the service (at least in the UI, I can't see the response as I see it with other services that return something).

Here I screenshot the docs, my dummy service, and the results:
![image](https://github.com/custom-components/pyscript/assets/2741256/51874969-2d06-4159-9fa7-5c3309bce105)

But when I trigger the service, no response data are returned:
![image](https://github.com/custom-components/pyscript/assets/2741256/4c0f6dc4-76ab-4cb0-80e1-67af30c41b95)

What am I missing?

**Comment by dmamelin** [comment]
```python
@service(supports_response="only")
def func()
```

**Comment by hnykda** [comment]
🤦 sorry
