### ISSUE TITLE
Croniter version conflict

### ISSUE THREAD

**Issue by dapuzz** [custom-components/pyscript#569]
Hi
the croniter version keeps to be overritten by the standard components/utility_meter/manifest.json:  "requirements": ["croniter==1.0.6"]

So every boot the system keep to install first version than the one from pyscript
/usr/local/bin/python3 -m pip install --quiet croniter==1.0.6
/usr/local/bin/python3 -m pip install --quiet croniter==1.3.8

Is this version really needed? Does the utility_meter will upgrade the croniter requirements?

Thank you

**Comment by rtasarz** [comment]
As of 2024.4 croniter requirement by utility_meter got bumped up to 2.0.2 so version mismatch continues. From what I've observed right now croniter is reinstalled with alternate version after each HA restart.
