### ISSUE TITLE
poorly formed state_trigger makes endless loop

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#57]
In testing #56 a typo ran me into a weird issue:

```python
@state_trigger('input_boolean.test_1 == "on"', state_hold=3)
@task.unique('test1')
def test():
    log.info('test_1 is on for 3')
    task.wait_until(state_trigger="input_boolean.test_2 = 'on'", state_hold=3, state_check_now=True)
    log.info('test_2 is on for 3')
```

Notice my `task.wait_until` improperly uses assignment in `state_trigger` instead of evaluation (single '=' instead of double '==').

Despite the `task.unique` and several reloads of pyscript, `input_boolean.test_2` stayed on regardless of my attempts to turn it off. I had to restart Home Assistant.

I'm not sure if a user error like this is detectable or preventable, but I imagine it'll bite someone else at some point.

**Comment by craigbarratt** [comment]
Ah good point - all trigger/active expressions are currently allowed to be any python code, including statements like assignments.  I'll shortly commit code that restricts them to only be expressions.  That will cause assignments (or any other statement) in trigger expressions to give a syntax error.

There are many ways to create infinite loops, for example if the trigger function does an assignment that causes a new trigger, eg:
```
@state_trigger("pyscript.dont_do_this")
def dont_do_this():
     pyscript.dont_do_this = int(pyscript.dont_do_this) + 1

pyscript.dont_do_this = 0
```
