### ISSUE TITLE
Exception in <file.pv_excess_control.on_time> line 246

### ISSUE THREAD

**Issue by githuber110** [custom-components/pyscript#590]
I have set up the blueprint according to the documentation, after running the automation I can see in the logbook that the script is triggered every 10 seconds, but nothing happens and the Appliance is not switched on although it should be based on the automation setup.

In the system log I see following error:

`This error originated from a custom integration.

Logger: custom_components.pyscript.file.pv_excess_control.on_time
Source: custom_components/pyscript/trigger.py:1268
Integration: Pyscript Python scripting (documentation, issues)
First occurred: March 1, 2024 at 23:50:21 (137 occurrences)
Last logged: 00:13:01

Exception in <file.pv_excess_control.on_time> line 246: first_item = next(iter(PvExcessControl.instances.values())) ^ RuntimeError: coroutine raised StopIteration`

Any idea what could be setup wrongly?

**Comment by ALERTua** [comment]
the setup is OK, but `next()` raises an exception due to no values found. I'd suggest assigning `list(iter(PvExcessControl.instances.values()))` to a variable, checking its length, and if it is not zero - then take the first element.

**Comment by githuber110** [comment]
Thank you, will check that.
