### ISSUE TITLE
Python 3.11 support removed from Home Assistant

### ISSUE THREAD

**Issue by kicker10BOG** [custom-components/pyscript#594]
As of now, Pyscript doesn't work with the latest Home Assistant (2024.4.0) because they removed Python 3.11 support.

I really like pyscript, so I hope this gets resolved.

**Comment by ALERTua** [comment]
Can you please provide the log output with the error?

**Comment by kicker10BOG** [comment]
I didn't see any error logs, but I will go back to 2024.4.0 later today/tonight when it's safe to have it not working again and check again. But none of my pyscript stuff seemed to be working after the upgrade yesterday, so I reverted to 2024.3.3

**Comment by ALERTua** [comment]
So the reason is not in Python 3.11. Maybe #569?

**Comment by kicker10BOG** [comment]
Tonight it's working fine. Maybe something happened during the update last night when I first tried it. When it didn't worked, I looked at the release notes and saw they removed Python 3.11 support and searched on this github to see if pyscript had been upgraded and saw no sign of it. My mistake.
