### ISSUE TITLE
tox.ini missing

### ISSUE THREAD

**Issue by basnijholt** [custom-components/pyscript#6]
I am trying to implement some new functionality which requires me to run the tests. 

However, it seems like the Tox configuration file is not committed.

**Comment by craigbarratt** [comment]
When I run pyscript tests I do it from a clone of [homeassistant core](https://github.com/home-assistant/core), which has a `tox.ini` file.  I thought it was easier doing it there since it has all the scaffolding, including via `script/setup` and `source venv/bin/activate` etc.
