### ISSUE TITLE
1.6 breaks automatic reload

### ISSUE THREAD

**Issue by archite** [custom-components/pyscript#622]
I upgraded to 1.6 and noticed that automatic reload no longer works. Leaving all settings the same and dropping back to 918b465, changes are picked up. I then replaced folder with that of 4b2e708, restarted HA and now I must manually reload changes. Further, triggers often fail on 1.6.0 versus those in 1.5 but I'm trying to narrow down more so until then, you can safely ignore.

**Comment by ALERTua** [comment]
I have this problem too

**Comment by craigbarratt** [comment]
This should be fixed in 1.6.1.

**Comment by archite** [comment]
Will try, thanks!

**Comment by archite** [comment]
This looks to have fixed it. Thank you!
