### ISSUE TITLE
need help --- Import not working in pyscript via HACS on HA

### ISSUE THREAD

**Issue by xenia-09A** [custom-components/pyscript#627]
Hi,
I'm struggling to get import working in pyscript via HACS on HA 2024.7.1.
any python file without an import works fine and I can run as service and show up in dev tools

then i simply add import requests for example I get this:

Exception in </config/pyscript/hello_world.py> line 2: i ^ SyntaxError: invalid syntax (hello_world.py, line 2)
Exception in </config/pyscript/hello_world.py> line 2: import requests ^ SyntaxError: invalid syntax (hello_world.py, line 2)

I tried to follow this guide by adding removing from yaml
https://hacs-pyscript.readthedocs.io/en/stable/reference.html#importing

my yaml config

pyscript:
  allow_all_imports: true
  hass_is_global: true

the doc above says this yaml will be ignored if GUI was used to install so I'm not sure what my settings need to be

my hello world.py file:
 
@service
import requests << won't load thus don't show up under dev tools and errors in log as provided

def hello_world():

thanks anyone in advance for any help to get this working

lastly when I listed all in requirment doc  logs stated  requests was already installed and ignoring 
2024-08-08 16:49:06.244 DEBUG (MainThread) [custom_components.pyscript] Skipping unpinned version of package 'requests' because version '2.32.3' is already installed

**Comment by xenia-09A** [comment]
also i now see this 
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 8:23:19 PM (4 occurrences)
Last logged: 8:23:46 PM

Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend_experimental", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 49: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by ALERTua** [comment]
```python
import requests

@service
def hello_workd():
    pass
```

**Comment by xenia-09A** [comment]
@ALERTua  

@ALERTua  thank you so much !!!   that helped having import above @service thanks   gosh I feel stupid!!
script now shows up in dev tools!

**Comment by ALERTua** [comment]
please close this issue if you have no further questions :)

**Comment by xenia-09A** [comment]
again thanks for the help .. I am having an issue seeing anything in logs but I keep at it 
I now  have this:

import requests
@service

def hello_world():
# testing requests
    url = "https://raw.githubusercontent.com/custom-components/pyscript/master/README.md"
    resp = task.executor(requests.get, url)
    log.info(f"Hello World")
    log.info(resp.text)

**Comment by xenia-09A** [comment]
closing a simple reboot of HA resolved @ALERTua thanks again

**Comment by xenia-09A** [comment]
thanks
