### ISSUE TITLE
no obvious way of uninstalling packages

### ISSUE THREAD

**Issue by Duck-Joke** [custom-components/pyscript#636]
is there a supported way of uninstalling packages installed through the "requirements" file? I mistakenly installed the adb-shell package, and now attempting to install adb-shell[usb] is giving me the "adb-shell[usb] wasn't able to be installed" error, presumably because of a conflict. I have encountered similar issues before with other libraries as well.

Did I miss a crucial part of the pyscript documentation? Or is there a way to access pip in console? (I am on raspberryPI 4 with Home Assistant OS)

**Comment by ALERTua** [comment]
- try adding the exact package version using `adb-shell[usb]==0.4.4` in your `requirements.txt`
- try adding `-U` (Upgrade) flag to the package in your `requirements.txt`
- try adding `--force` flag to the package in your `requirements.txt`
- try managing pip packages from within Python
```python
from pip._internal import main as pipmain
pipmain(['uninstall', 'adb-shell'])
pipmain(['install', 'adb-shell[usb]'])
```

**Comment by Duck-Joke** [comment]
worked, thank you 🙏
