### ISSUE TITLE
Feature Request: methods on entity_ids

### ISSUE THREAD

**Issue by dlashua** [custom-components/pyscript#64]
It would be a nice language feature if entity id's could have service calls made against them as though they were real python objects. When this syntax is invoked, it would result in a service_call with the entity_id kwarg set to the entity_id it was called on.

Example Script that works today:
```python
@state_trigger('input_boolean.test_1 == "on"')
def do_it():
  input_boolean.turn_on(entity_id="input_boolean.test_2")
```

Proposed Possible Syntax:
```python
@state_trigger('input_boolean.test_1 == "on"')
def do_it():
  input_boolean.test_2.turn_on()
```

This should be enabled for all entity_ids in any domain:
```python
climate.set_preset_mode(entity_id="climate.hvac", preset_mode="home")
climate.hvac.set_preset_mode(preset_mode="home")

input_number.set_value(entity_id="input_number.test", value="13")
input_number.test.set_value(value="13")

input_select.select_option(entity_id="input_select.dishwasher_status", option="clean")
input_select.dishwasher_status.select_option(option="clean")
```

This makes the code look cleaner and more readable. It also prevents the need to type "input_number" (for instance) twice, and prevents the need to type "entity_id" at all.

An even better extension of this proposal would require a hardcoded list to be kept and maintained in pyscript since I don't believe this information is provided by HASS (though it might be detectable by the parameter information given when HASS enumerates available service calls). Service calls that only require two kwargs -- entity_id and one other thing -- could have the kwarg for that other thing hard coded (or somehow detected). For instance, for input_number.set_value, the other kwarg is `value`. If pyscript knew this then this syntax would be possible:
```python
input_number.set_value(entity_id="input_number.test", value="13")
input_number.test.set_value(value="13")
input_number.test.set_value("13")
```

**Comment by raman325** [comment]
You can get the parameters for a given service from `homeassistant.helpers.service.async_get_all_descriptions`. It appears that the descriptions are cached by `hass` so calling this method shouldn't be a terribly expensive operation.

**Comment by craigbarratt** [comment]
Yes, that's exactly the approach I'm taking.  I just call it once at startup and reload to extract the services that have an `entity_id` parameter and use that to create the "methods".

**Comment by craigbarratt** [comment]
This is a very clever idea!  Thanks for suggesting it.

I just pushed an implementation of this, including autodetecting `entity_id` arguments as @raman325 suggested, and allowing a single positional argument if there is only one parameter left over.

I still haven't added tests or docs, but give it a try.  Autocompletion in Jupyter should work too. Hopefully I'll add tests and docs tomorrow.

The virtual methods take precedence over real attributes. If there is a name collision you could use `state.get_attr()` (which by the way I probably should have named `state.getattr()`; maybe I'll change that).

**Comment by dlashua** [comment]
I've tested this and it's working great!! Thanks!!

**Comment by rytilahti** [comment]
I didn't realize that this is soo new feature, but works fine here, too! I'm currently taking the first steps to covert my old appdaemon apps, and I incidentally used the syntax not realizing it wouldn't have worked had I done this yesterday. Thanks @craigbarratt for this project, it's awesome! :1st_place_medal:

**Comment by craigbarratt** [comment]
@rytilahti - that's quite a coincidence! Glad it works for you too. Appreciate the feedback and feel free to pass along any suggestions or feature requests.
