### ISSUE TITLE
state trigger on DOMAIN.name.attr gets old_value from name not attr

### ISSUE THREAD

**Issue by dy-nz** [custom-components/pyscript#641]
Hi.
Love pyscript - best thing that happened to HA.
But I have bumped into a small but problematic bug.

@state_trigger("media_player.chromecast.app_name")
def test(trigger_type=None, var_name=None, value=None, old_value=None):
      etc, etc...

The state_trigger correctly triggers, but old_value is set to the old value of media_player.chromecast (example "off") when it should be set to the old value of media_player.chromecast.app_name (example "Spotify")

Thanks,
David

**Comment by craigbarratt** [comment]
Please try `old_value.app_name` inside the function.   The `value` and `old_value` are always set to the variable value (including attributes), even if you trigger off an attribute.

**Comment by dy-nz** [comment]
Thanks.
