### ISSUE TITLE
Feature Request: Add logging for life-cycle changes

### ISSUE THREAD

**Issue by rytilahti** [custom-components/pyscript#75]
I find myself using the following pattern to make it easier to grep through logs to see if the script has been loaded:
```
@time_trigger
def run_on_startup_or_reload():
    log.info(f"Loading {__name__}")
```

It would be great if the "core" would do that on my behalf to avoid code duplication. I have a locally added info-level message under `__init__.load_scripts`, but I'm not sure if that's really the correct place to add such. Ideas/opinions?

**Comment by craigbarratt** [comment]
Good idea - perhaps this `debug` message should be moved to the end of the function (ie, on success) and made an `info` message:

https://github.com/custom-components/pyscript/blob/666e3fcb42dbf3a233be74cb880fc9f45e3b3fcc/custom_components/pyscript/global_ctx.py#L269

Currently pyscript only has `info` messages for starting/stopping a Jupyter session.  While I don't like cluttering the logs, loading a new pyscript script or app seems like a worthy thing to appear in the log.
