### ISSUE TITLE
Add configuration option to allow all imports

### ISSUE THREAD

**Issue by basnijholt** [custom-components/pyscript#8]
With every update, I remove a few lines that check whether the import I do is allowed.

Something like

```yaml
pyscript:
  allow_all_imports: true
```

**Comment by craigbarratt** [comment]
Yes, that's a great idea.  It's mentioned in the [wiki roadmap](https://github.com/custom-components/pyscript/wiki/Roadmap-for-Pyscript).

**Comment by craigbarratt** [comment]
Thanks for the PR - merged.
