### ISSUE TITLE
task.wait_until ignores state_check_now

### ISSUE THREAD

**Issue by dadler** [custom-components/pyscript#81]
The task.wait_until() function always checks state on entry, ignoring the documented state_check_now argument.  In fact the state_check_now argument of wait_until() in trigger.py is declared but never used.

pyscript version: 0.32

**Comment by dlashua** [comment]
I believe this is fixed in master and will be in the next release.

**Comment by craigbarratt** [comment]
Yes, that 's correct - it was fixed in 1a7b665 a couple of weeks ago. I'll add it to the fixed bug list in `docs/new_features.rst`.
