### ISSUE TITLE
no way to prevent state_set from removes existing attributes

### ISSUE THREAD

**Issue by fleXible** [custom-components/pyscript#9]
Hi,

using `state.set("domain.entity", "new state")` removes existing attributes. It is possible to supply an attribute dict, but there was no way of collecting all existing attributes from a state. `state.get()` only supported pulling a single attribute by name.

Also `state_get()` would not return the full State object, but only the state as string or the attribute value.

As a possible way to fix this, I did some changes:
- Add `states` object, known from [template extensions](https://www.home-assistant.io/docs/configuration/templating/) to be the new way of simple state retrievals
- Add new method `get_new` that returns the actual State object and remapped `state.get()` to it
- Add new method `set_new` that preserves existing attributes by default, but also allowes them to be updated or removed

The PR will follow soon.

**Comment by craigbarratt** [comment]
Good suggestions- it would be good to have a clean way of providing those features.  This is related to issues #11 and #12.

**Comment by craigbarratt** [comment]
I just made a commit 712692f that makes state setting preserve the attributes.  `state.set()` can optionally update or replace attributes.  I also added `state.get_attr()` to get a dict of all attributes for a state variable.

**Comment by craigbarratt** [comment]
This is released in 0.21.

If you can suggest additional features or changes, please re-open this issue or create a new one.

**Comment by fleXible** [comment]
@craigbarratt 
In my PR I also fancied the idea to have access to the full `State`object, maybe to access any of the other available properties like `last_changed`or `context`.

And I suggested using the `states`objects from HAs template engine. Even though the way I implemented it, was quite ugly, still it lets you iterate over all states or thos from a specific domain and gives access to the full `State` object.
I liked it, because it works the same way as in templates, making it easier for people to adopt `pyscript`.

What do you think?
