### ISSUE TITLE
Variable not defined when using state.persist

### ISSUE THREAD

**Issue by github392** [custom-components/pyscript#96]
I have started to use state.persist() but I have a problem with unknown variable. I have this kind of code

``````
state.persist('pyscript.test')

@service
def test_var(value=None):
    pyscript.test= float(pyscript.test) + 1
``````

2020-11-28 11:16:39 ERROR (MainThread) [custom_components.pyscript.file.energy.test_var] Exception in <file.energy.test_var> line 22:
pyscript.test= float(pyscript.test) + 1
^
NameError: name 'pyscript.test' is not defined

I have as a workaround put  pyscript.test=0 in my code
``````
state.persist('pyscript.test')
pyscript.test=0

@service
def test_var(value=None):
    pyscript.test= float(pyscript.test) + 1
``````
and run once and the removed that statement pyscript.test=0 but what is the correct way to initialize these kind of variable?

**Comment by dlashua** [comment]
`state.persist` does not set the state unless you tell it to, like so:

```
state.persist('pyscript.test', default_value="0", default_attributes={"friendly_name": "Test"})
```

 When I'm not certain an entity exists or that it will have a value I expect I use a certain code pattern. This can happen even when not using persist. For instance, when you expect a float-like string but the sensor says "unavailable", or as Home Assistant is starting up and certain entities aren't created yet. 

```
try:
  pyscript.test = float(pyscript.test) + 1
except NameError: #This will catch when the entity doesn't exist
  pyscript.test = 1
except ValueError: #This will catch when the value is not float-like
  pyscript.test = 1
```

**Comment by github392** [comment]
Ahh missed that part in doc. Thanks for pointing me in that direction.
